<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Individualized cost-effectiveness analysis (iCEA) • hesim</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/simplex/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<meta property="og:title" content="Individualized cost-effectiveness analysis (iCEA)">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<meta name="robots" content="noindex">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">hesim</a>
        <span class="version label label-danger" data-toggle="tooltip" data-placement="bottom" title="In-development version">0.2.2.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">API</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/intro.html">Introduction to hesim</a>
    </li>
    <li class="divider">
    <li class="dropdown-header">Markov cohort models</li>
    <li>
      <a href="../articles/getting-started.html">Getting started with a Markov cohort model</a>
    </li>
    <li>
      <a href="../articles/markov-inhomogeneous.html">Time inhomogeneous Markov cohort model</a>
    </li>
    <li class="divider">
    <li class="dropdown-header">Statistical models of disease progression</li>
    <li>
      <a href="../articles/mlogit.html">Markov models with multinomial logistic regression</a>
    </li>
    <li>
      <a href="../articles/psm.html">Partitioned survival models</a>
    </li>
    <li>
      <a href="../articles/mstate.html">Markov and semi-Markov multi-state models</a>
    </li>
    <li class="divider">
    <li class="dropdown-header">Economic analysis</li>
    <li>
      <a href="../articles/expected-values.html">Simulating costs and quality-adjusted life-years</a>
    </li>
    <li>
      <a href="../articles/icea.html">Individualized cost-effectiveness analysis</a>
    </li>
    <li class="divider">
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/hesim-dev/hesim">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Individualized cost-effectiveness analysis (iCEA)</h1>
            
            <h4 class="date">2020-03-08</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/hesim-dev/hesim/blob/master/vignettes/icea.Rmd"><code>vignettes/icea.Rmd</code></a></small>
      <div class="hidden name"><code>icea.Rmd</code></div>

    </div>

    
    
<div id="overview" class="section level1">
<h1 class="hasAnchor">
<a href="#overview" class="anchor"></a><span class="header-section-number">1</span> Overview</h1>
<p>Individualized cost-effectiveness analysis (iCEA) evaluates the cost-effectiveness of treatments at the individual (or subgroup) level. This has two major implications:</p>
<ul>
<li>Optimal treatments will vary across patients.</li>
<li>Treatments will be more cost-effective for some patients than others.</li>
</ul>
<p>The <code>hesim</code> package help facilitate iCEA by providing a number of functions for analyzing subgroup level health and cost outcomes from simulation models that quantify parameter uncertainty using probabilistic sensitivity analysis (PSA). These functions take simulation output and generate measures commonly used for technology assessment including:</p>
<ul>
<li>net monetary benefits (NMBs).</li>
<li>incremental cost-effectiveness ratios (ICERs).</li>
<li>cost-effectiveness acceptability curves (CEACs).</li>
<li>the expected value of perfect information (EVPI).</li>
</ul>
<p>The rest of this document provides an overview of iCEA and how it can be conducted using <code>hesim</code>. The perspective is Bayesian in nature in that it is concerned with estimating the entire distribution of outcomes rather than just expected values <span class="citation">(Baio 2012; Baio and Dawid 2015)</span>. It also stresses that both optimal treatments and the cost-effectiveness of those treatments vary across individuals <span class="citation">(Basu and Meltzer 2007; Espinoza et al. 2014)</span>.</p>
</div>
<div id="net-monetary-benefits" class="section level1">
<h1 class="hasAnchor">
<a href="#net-monetary-benefits" class="anchor"></a><span class="header-section-number">2</span> Net monetary benefits</h1>
<p>Decision analysis provides a formal framework for making treatment decisions based on the utility that a therapy provides to a patient population. Decisions are typically made using a net benefit approach grounded in expected utility theory. The optimal treatment strategy is the one that maximizes expected NMBs where expected NMBs are calculated by averaging over the patient population and uncertain parameters <span class="math inline">\(\theta\)</span>. For a given subgroup <span class="math inline">\(g\)</span> and parameter set <span class="math inline">\(\theta\)</span>, NMBs are computed as the difference between the monetized health gains from an intervention less costs, or,</p>
<p><span class="math display">\[
\begin{aligned}
NMB_g(j,\theta) = e_{gj}\cdot k- c_{gj},
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(e_{gj}\)</span> and <span class="math inline">\(c_{gj}\)</span> are measures of clinical effectiveness (e.g. QALYs) and costs in subgroup <span class="math inline">\(g\)</span> using treatment <span class="math inline">\(j\)</span> respectively, and <span class="math inline">\(k\)</span> is a decision makers willingness to pay per unit of clinical effectiveness. The optimal treatment for a given subgroup is the one that maximizes expected NMBs,</p>
<p><span class="math display">\[
\begin{aligned}
j^{*}_g = \text{argmax}_j E_{\theta} \left[NMB_g(j,\theta)\right].
\end{aligned}
\]</span></p>
<p>In practice, new interventions are usually compared to a standard treatment often referred to as the comparator. In these cases, a new treatment in a given subgroup is preferred to the comparator if the expected incremental net monetary benefit (INMB) of the new treatment is positive; that is, treatment 1 is preferred to treatment 0 in subgroup <span class="math inline">\(g\)</span> if <span class="math inline">\(E_\theta \left[INMB_g\right] &gt; 0\)</span> where the INMB in a particular subgroup is given by</p>
<p><span class="math display">\[
\begin{aligned}
INMB_g(\theta) = NMB_g(j = 1, \theta) - NMB_g(j = 0, \theta).
\end{aligned}
\]</span> Equivalently, treatment <span class="math inline">\(1\)</span> is preferred to treatment <span class="math inline">\(0\)</span> in subgroup <span class="math inline">\(g\)</span> if the incremental cost-effectiveness ratio (ICER) is greater than the willingness to pay threshold <span class="math inline">\(k\)</span>,</p>
<p><span class="math display">\[
\begin{aligned}
k &gt; \frac{c_{g1} - c_{s0}}{e_{g1} - e_{g0}} = ICER_g.
\end{aligned}
\]</span></p>
</div>
<div id="probabilistic-sensitivity-analysis" class="section level1">
<h1 class="hasAnchor">
<a href="#probabilistic-sensitivity-analysis" class="anchor"></a><span class="header-section-number">3</span> Probabilistic sensitivity analysis</h1>
<p>Expected NMBs are expected values and ignore parameter uncertainty. This implies that NMBs are uncertain and that optimal treatment strategies may be selected incorrectly. This uncertainty can be quantified using PSA, which uses Bayesian and quasi-Bayesian techniques to estimate the distribution of NMBs given the distribution of the parameters for each treatment strategy</p>
<p>Since the joint distribution of the model parameters cannot be derived analytically (except in the simplest cases), the distribution of <span class="math inline">\(\theta\)</span> is approximated by simulating the parameters from their joint posterior distribution and calculating relevant quantities of interest as a function of the simulated parameters. For each treatment strategy and subgroup, PSA therefore produces <span class="math inline">\(n\)</span> random draws from the posterior distribution of clinical effectiveness and costs,</p>
<p><span class="math display">\[
\begin{aligned}
e_{gj} &amp;= [e_{gj}^1, e_{gj}^2, \dots, e_{gj}^n] \\
c_{gj} &amp;= [c_{gj}^1, c_{gj}^2, \dots, c_{gj}^n].
\end{aligned}
\]</span></p>
<p>Below we simulate costs and QALYs for three treatment strategies and two subgroups (in a real world analysis, this output would be derived from a detailed health-economic simulation model). Strategy 1 is the current standard of care; it is the cheapest therapy, but also the least efficacious. Strategies 2 and 3 are equally costly, but Strategy 2 is more effective in subgroup 1 while Strategy 3 is more effective in subgroup 2.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Random">set.seed</a></span>(<span class="dv">131</span>)</span>
<span id="cb1-2"><a href="#cb1-2"></a>n_samples &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># cost</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>c &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/vector">vector</a></span>(<span class="dt">mode =</span> <span class="st">"list"</span>, <span class="dt">length =</span> <span class="dv">6</span>)</span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(c) &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"Strategy 1, Grp 1"</span>, <span class="st">"Strategy 1, Grp 2"</span>, <span class="st">"Strategy 2, Grp 1"</span>,</span>
<span id="cb1-7"><a href="#cb1-7"></a>              <span class="st">"Strategy 2, Grp 2"</span>, <span class="st">"Strategy 3, Grp 1"</span>, <span class="st">"Strategy 3, Grp 2"</span>)</span>
<span id="cb1-8"><a href="#cb1-8"></a>c[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Lognormal">rlnorm</a></span>(n_samples, <span class="dv">2</span>, <span class="fl">.1</span>)</span>
<span id="cb1-9"><a href="#cb1-9"></a>c[[<span class="dv">2</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Lognormal">rlnorm</a></span>(n_samples, <span class="dv">2</span>, <span class="fl">.1</span>)</span>
<span id="cb1-10"><a href="#cb1-10"></a>c[[<span class="dv">3</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Lognormal">rlnorm</a></span>(n_samples, <span class="dv">11</span>, <span class="fl">.15</span>)</span>
<span id="cb1-11"><a href="#cb1-11"></a>c[[<span class="dv">4</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Lognormal">rlnorm</a></span>(n_samples, <span class="dv">11</span>, <span class="fl">.15</span>)</span>
<span id="cb1-12"><a href="#cb1-12"></a>c[[<span class="dv">5</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Lognormal">rlnorm</a></span>(n_samples, <span class="dv">11</span>, <span class="fl">.15</span>)</span>
<span id="cb1-13"><a href="#cb1-13"></a>c[[<span class="dv">6</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Lognormal">rlnorm</a></span>(n_samples, <span class="dv">11</span>, <span class="fl">.15</span>)</span>
<span id="cb1-14"><a href="#cb1-14"></a></span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="co"># effectiveness</span></span>
<span id="cb1-16"><a href="#cb1-16"></a>e &lt;-<span class="st"> </span>c</span>
<span id="cb1-17"><a href="#cb1-17"></a>e[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Normal">rnorm</a></span>(n_samples, <span class="dv">8</span>, <span class="fl">.2</span>)</span>
<span id="cb1-18"><a href="#cb1-18"></a>e[[<span class="dv">2</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Normal">rnorm</a></span>(n_samples, <span class="dv">8</span>, <span class="fl">.2</span>)</span>
<span id="cb1-19"><a href="#cb1-19"></a>e[[<span class="dv">3</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Normal">rnorm</a></span>(n_samples, <span class="dv">10</span>, <span class="fl">.8</span>)</span>
<span id="cb1-20"><a href="#cb1-20"></a>e[[<span class="dv">4</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Normal">rnorm</a></span>(n_samples, <span class="fl">10.5</span>, <span class="fl">.8</span>)</span>
<span id="cb1-21"><a href="#cb1-21"></a>e[[<span class="dv">5</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Normal">rnorm</a></span>(n_samples, <span class="fl">8.5</span>, <span class="fl">.6</span>)</span>
<span id="cb1-22"><a href="#cb1-22"></a>e[[<span class="dv">6</span>]] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Normal">rnorm</a></span>(n_samples, <span class="dv">11</span>, <span class="fl">.6</span>)</span>
<span id="cb1-23"><a href="#cb1-23"></a></span>
<span id="cb1-24"><a href="#cb1-24"></a><span class="co"># cost and effectiveness by strategy and simulation</span></span>
<span id="cb1-25"><a href="#cb1-25"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"data.table"</span>)</span>
<span id="cb1-26"><a href="#cb1-26"></a>ce &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/data.table">data.table</a></span>(<span class="dt">sample =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(n_samples), <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(e)),</span>
<span id="cb1-27"><a href="#cb1-27"></a>                 <span class="dt">strategy =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste0</a></span>(<span class="st">"Strategy "</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">1</span>, <span class="dv">3</span>)), </span>
<span id="cb1-28"><a href="#cb1-28"></a>                                <span class="dt">each =</span> n_samples <span class="op">*</span><span class="st"> </span><span class="dv">2</span>),</span>
<span id="cb1-29"><a href="#cb1-29"></a>                 <span class="dt">grp =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"Group 1"</span>, <span class="st">"Group 2"</span>),</span>
<span id="cb1-30"><a href="#cb1-30"></a>                               <span class="dt">each =</span> n_samples), <span class="dv">3</span>),</span>
<span id="cb1-31"><a href="#cb1-31"></a>                 <span class="dt">cost =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/do.call">do.call</a></span>(<span class="st">"c"</span>, c), <span class="dt">qalys =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/do.call">do.call</a></span>(<span class="st">"c"</span>, e))</span>
<span id="cb1-32"><a href="#cb1-32"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(ce)</span></code></pre></div>
<pre><code>##    sample   strategy     grp     cost    qalys
## 1:      1 Strategy 1 Group 1 6.808115 7.984456
## 2:      2 Strategy 1 Group 1 6.997936 7.984085
## 3:      3 Strategy 1 Group 1 8.183247 8.221359
## 4:      4 Strategy 1 Group 1 7.423647 8.155250
## 5:      5 Strategy 1 Group 1 7.063846 8.292916
## 6:      6 Strategy 1 Group 1 7.234418 8.066187</code></pre>
<p>For any given willingness to pay <span class="math inline">\(k\)</span>, expected NMBs can be calculated by strategy, subgroup, and simulation number. For example, with <span class="math inline">\(k=150,000\)</span>, a reasonable estimate of the value of a life-year in the United States, Strategy 2 provides the highest expected NMBs in subgroup 2 while Strategy 3 provides the highest expected NMBs in subgroup 2.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>ce &lt;-<span class="st"> </span>ce[, nmb <span class="op">:</span><span class="er">=</span><span class="st"> </span><span class="dv">150000</span> <span class="op">*</span><span class="st"> </span>qalys <span class="op">-</span><span class="st"> </span>cost]</span>
<span id="cb3-2"><a href="#cb3-2"></a>enmb &lt;-<span class="st"> </span>ce[, .(<span class="dt">enmb =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/mean">mean</a></span>(nmb)), by =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"strategy"</span>, <span class="st">"grp"</span>)]</span>
<span id="cb3-3"><a href="#cb3-3"></a>enmb &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/dcast.data.table">dcast</a></span>(enmb, strategy <span class="op">~</span><span class="st"> </span>grp, <span class="dt">value.var =</span> <span class="st">"enmb"</span>)</span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(enmb)</span></code></pre></div>
<pre><code>##      strategy Group 1 Group 2
## 1: Strategy 1 1200672 1200323
## 2: Strategy 2 1447770 1509467
## 3: Strategy 3 1215793 1589370</code></pre>
<p>A number of measures have been proposed in the health economics literature to summarize the PSA. Below we describe the most common measures, which can be calculated using the functions <code>icea</code> and <code>icea_pw</code>. The <code>icea</code> function summarizes results by taking into account each treatment strategy in the analysis, while the function <code>icea_pw</code> summarizes “pairwise” results in which each treatment is compared to a comparator.</p>
<p>We can use the <code>icea</code> function to summarize results from our <code>data.table</code> object of simulated output for a range of willingness to pay values,</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"hesim"</span>)</span>
<span id="cb5-2"><a href="#cb5-2"></a>ktop &lt;-<span class="st"> </span><span class="dv">200000</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>icea &lt;-<span class="st">  </span><span class="kw"><a href="../reference/icea.html">icea</a></span>(ce, <span class="dt">k =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, ktop, <span class="dv">500</span>), <span class="dt">sample =</span> <span class="st">"sample"</span>, <span class="dt">strategy =</span> <span class="st">"strategy"</span>,</span>
<span id="cb5-4"><a href="#cb5-4"></a>                 <span class="dt">grp =</span> <span class="st">"grp"</span>, <span class="dt">e =</span> <span class="st">"qalys"</span>, <span class="dt">c =</span> <span class="st">"cost"</span>)</span></code></pre></div>
<p>The most important input in <code>icea</code> is the <code>data.table</code> object (<code>x</code>) containing columns for simulation number (<code>sim</code>), treatment strategy (<code>strategy</code>), subgroup (<code>grp</code>), clinical effectiveness (<code>e</code>), and costs (<code>c</code>). Users specify the names of the relevant columns in their output table as strings. The other relevant parameter is <span class="math inline">\(k\)</span>, which is a range of willingness to pay values to use for estimating NMBs.</p>
<p>Likewise, we can use <code>icea_pw</code> to summarize the PSA when directly comparing the two treatment strategies (Strategy 2 and Strategy 3) to the comparator (Strategy 1).</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>icea_pw &lt;-<span class="st">  </span><span class="kw"><a href="../reference/icea.html">icea_pw</a></span>(ce,  <span class="dt">k =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, ktop, <span class="dv">500</span>), <span class="dt">comparator =</span> <span class="st">"Strategy 1"</span>,</span>
<span id="cb6-2"><a href="#cb6-2"></a>                       <span class="dt">sample =</span> <span class="st">"sample"</span>, <span class="dt">strategy =</span> <span class="st">"strategy"</span>, <span class="dt">grp =</span> <span class="st">"grp"</span>,</span>
<span id="cb6-3"><a href="#cb6-3"></a>                    <span class="dt">e =</span> <span class="st">"qalys"</span>, <span class="dt">c =</span> <span class="st">"cost"</span>)</span></code></pre></div>
<p>The same inputs are used as in <code>icea</code> except users must specify the name of the comparator strategy.</p>
<div id="probability-most-cost-effective" class="section level2">
<h2 class="hasAnchor">
<a href="#probability-most-cost-effective" class="anchor"></a><span class="header-section-number">3.1</span> Probability most cost-effective</h2>
<p>A useful summary measure for quantifying uncertainty is the probability that each treatment strategy is the most cost effective. For a particular subgroup, this is estimated from simulation output as the proportion of simulation draws that each strategy has the highest NMB. For example, consider a random sample of 10 draws from the PSA simulation output and suppose <span class="math inline">\(k\)</span> is again equal to <span class="math inline">\(150,000\)</span>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>random_rows &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sample">sample</a></span>(<span class="dv">1</span><span class="op">:</span>n_samples, <span class="dv">10</span>)</span>
<span id="cb7-2"><a href="#cb7-2"></a>nmb_dt &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/dcast.data.table">dcast</a></span>(ce[sample <span class="op">%in%</span><span class="st"> </span>random_rows <span class="op">&amp;</span><span class="st"> </span>grp <span class="op">==</span><span class="st"> "Group 2"</span>], </span>
<span id="cb7-3"><a href="#cb7-3"></a>                sample <span class="op">~</span><span class="st"> </span>strategy, <span class="dt">value.var =</span> <span class="st">"nmb"</span>)</span>
<span id="cb7-4"><a href="#cb7-4"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/setattr">setnames</a></span>(nmb_dt, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/colnames">colnames</a></span>(nmb_dt), <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"sample"</span>, <span class="st">"nmb1"</span>, <span class="st">"nmb2"</span>, <span class="st">"nmb3"</span>))</span>
<span id="cb7-5"><a href="#cb7-5"></a>nmb_dt &lt;-<span class="st"> </span>nmb_dt[, maxj <span class="op">:</span><span class="er">=</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/apply">apply</a></span>(nmb_dt[, .(nmb1, nmb2, nmb3)], <span class="dv">1</span>, which.max)]</span>
<span id="cb7-6"><a href="#cb7-6"></a>nmb_dt &lt;-<span class="st"> </span>nmb_dt[, maxj <span class="op">:</span><span class="er">=</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(maxj, <span class="dt">levels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))]</span></code></pre></div>
<table class="table">
<thead><tr>
<th style="text-align:right;">
sample
</th>
<th style="text-align:right;">
nmb1
</th>
<th style="text-align:right;">
nmb2
</th>
<th style="text-align:right;">
nmb3
</th>
<th style="text-align:left;">
maxj
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
76
</td>
<td style="text-align:right;">
1202301
</td>
<td style="text-align:right;">
1636179
</td>
<td style="text-align:right;">
1567846
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
373
</td>
<td style="text-align:right;">
1200018
</td>
<td style="text-align:right;">
1607944
</td>
<td style="text-align:right;">
1623927
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
428
</td>
<td style="text-align:right;">
1204742
</td>
<td style="text-align:right;">
1534322
</td>
<td style="text-align:right;">
1566590
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
494
</td>
<td style="text-align:right;">
1235582
</td>
<td style="text-align:right;">
1441176
</td>
<td style="text-align:right;">
1720674
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
591
</td>
<td style="text-align:right;">
1218996
</td>
<td style="text-align:right;">
1108168
</td>
<td style="text-align:right;">
1542916
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
645
</td>
<td style="text-align:right;">
1217311
</td>
<td style="text-align:right;">
1504604
</td>
<td style="text-align:right;">
1586612
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
735
</td>
<td style="text-align:right;">
1192570
</td>
<td style="text-align:right;">
1537154
</td>
<td style="text-align:right;">
1379873
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
807
</td>
<td style="text-align:right;">
1213061
</td>
<td style="text-align:right;">
1420991
</td>
<td style="text-align:right;">
1359655
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
860
</td>
<td style="text-align:right;">
1209484
</td>
<td style="text-align:right;">
1345773
</td>
<td style="text-align:right;">
1503219
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
995
</td>
<td style="text-align:right;">
1197708
</td>
<td style="text-align:right;">
1495210
</td>
<td style="text-align:right;">
1518871
</td>
<td style="text-align:left;">
3
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>mce &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/prop.table">prop.table</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/table">table</a></span>(nmb_dt<span class="op">$</span>maxj))</span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(mce)</span></code></pre></div>
<pre><code>## 
##   1   2   3 
## 0.0 0.3 0.7</code></pre>
<p>In this example, treatments 1, 2, and 3 have the highest NMBs a fraction 0, 0.3, and 0.7 of the time respectively. The <code>icea</code> function performs this same calculations for a range of values of <span class="math inline">\(k\)</span> and all <code>nsims</code> random draws of the simulation output. The output is a tidy <code>data.table</code> which facilitates plotting with <code>ggplot</code>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"scales"</span>)</span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme_get.html">theme_set</a></span>(<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span>())</span>
<span id="cb10-4"><a href="#cb10-4"></a>ggplot2<span class="op">::</span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(icea<span class="op">$</span>mce, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> prob, <span class="dt">col =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(strategy))) <span class="op">+</span></span>
<span id="cb10-5"><a href="#cb10-5"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="op">~</span>grp) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"Willingness to pay"</span>) <span class="op">+</span></span>
<span id="cb10-6"><a href="#cb10-6"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"Probability most cost-effective"</span>) <span class="op">+</span></span>
<span id="cb10-7"><a href="#cb10-7"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> scales<span class="op">::</span>dollar) <span class="op">+</span></span>
<span id="cb10-8"><a href="#cb10-8"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Strategy"</span>)</span></code></pre></div>
<p><img src="icea_files/figure-html/mce_plot-1.png" width="672"></p>
<p>In group 1, Strategy 2 provides the greatest NMBs with high probability for almost all reasonable values of k. In group 2, the results are less certain, although Strategy 3 provides the greatest NMBs with a higher probability than Strategy 2.</p>
</div>
<div id="cost-effectiveness-acceptability-frontier-ceaf" class="section level2">
<h2 class="hasAnchor">
<a href="#cost-effectiveness-acceptability-frontier-ceaf" class="anchor"></a><span class="header-section-number">3.2</span> Cost-effectiveness acceptability frontier (CEAF)</h2>
<p>One drawback of the previous plot is that the probability of being cost-effective cannot be used to determine the optimal treatment option. Instead, if a decision-makers objective is to maximize health gain, then decisions should be based on the expected net monetary benefit <span class="citation">(Barton, Briggs, and Fenwick 2008)</span>. The cost-effectiveness acceptability frontier (CEAF), which plots the probability that the optimal treatment strategy (i.e., the strategy with the highest expected NMB) is cost-effective, is appropriate in this context.</p>
<p>A CEAF curve can be easily created by using the <code>best</code> column to subset to the treatment strategy with the highest expected NMB for each willingness to pay value and group.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>ggplot2<span class="op">::</span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(icea<span class="op">$</span>mce[best <span class="op">==</span><span class="st"> </span><span class="dv">1</span>], <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> prob, <span class="dt">col =</span> strategy)) <span class="op">+</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="op">~</span>grp) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"Willingness to pay"</span>) <span class="op">+</span></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"Probability most cost-effective"</span>) <span class="op">+</span></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> scales<span class="op">::</span>dollar) <span class="op">+</span></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Strategy"</span>)</span></code></pre></div>
<p><img src="icea_files/figure-html/ceaf_plot-1.png" width="672"></p>
</div>
<div id="value-of-perfect-information" class="section level2">
<h2 class="hasAnchor">
<a href="#value-of-perfect-information" class="anchor"></a><span class="header-section-number">3.3</span> Value of perfect information</h2>
<p>One draw back of the previous measure is that it ignores the magnitude of cost or QALY gains. A measure which combines the probability of being most effective with the magnitude of the expected NMB is the expected value of perfect information (EVPI). Intuitively, the EVPI provides an estimate of the amount that a decision maker would be willing to pay to collect additional data and completely eliminate uncertainty. Mathematically, the EVPI is defined as the difference between the maximum expected NMB given perfect information and the maximum expected NMB given current information. In other words, we calculate the NMB for the optimal treatment strategy for each random draw of the parameters and compare that to the NMB for the treatment strategy that is optimal when averaging across all parameters. Mathematically, the EVPI for subgroup <span class="math inline">\(g\)</span> is,</p>
<p><span class="math display">\[
\begin{aligned}
EVPI_g &amp;= E_\theta \left[max_j NMB_g(j, \theta)\right] - max_j E_\theta \left [ NMB_g(j, \theta)\right]. \\
\end{aligned}
\]</span></p>
<p>To illustrate consider the same random sample of 10 draws from our simulation output used above.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>strategymax_g2 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.max</a></span>(enmb[[<span class="dv">3</span>]])</span>
<span id="cb12-2"><a href="#cb12-2"></a>nmb_dt &lt;-<span class="st"> </span>nmb_dt[, nmbpi <span class="op">:</span><span class="er">=</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/apply">apply</a></span>(nmb_dt[, .(nmb1, nmb2, nmb3)], <span class="dv">1</span>, max)]</span>
<span id="cb12-3"><a href="#cb12-3"></a>nmb_dt &lt;-<span class="st"> </span>nmb_dt[, nmbci <span class="op">:</span><span class="er">=</span><span class="st"> </span>nmb_dt[[strategymax_g2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>]]]</span>
<span id="cb12-4"><a href="#cb12-4"></a><span class="kw">kable</span>(nmb_dt, <span class="dt">digits =</span> <span class="dv">0</span>, <span class="dt">format =</span> <span class="st">"html"</span>)</span></code></pre></div>
<table class="table">
<thead><tr>
<th style="text-align:right;">
sample
</th>
<th style="text-align:right;">
nmb1
</th>
<th style="text-align:right;">
nmb2
</th>
<th style="text-align:right;">
nmb3
</th>
<th style="text-align:left;">
maxj
</th>
<th style="text-align:right;">
nmbpi
</th>
<th style="text-align:right;">
nmbci
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
76
</td>
<td style="text-align:right;">
1202301
</td>
<td style="text-align:right;">
1636179
</td>
<td style="text-align:right;">
1567846
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
1636179
</td>
<td style="text-align:right;">
1567846
</td>
</tr>
<tr>
<td style="text-align:right;">
373
</td>
<td style="text-align:right;">
1200018
</td>
<td style="text-align:right;">
1607944
</td>
<td style="text-align:right;">
1623927
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1623927
</td>
<td style="text-align:right;">
1623927
</td>
</tr>
<tr>
<td style="text-align:right;">
428
</td>
<td style="text-align:right;">
1204742
</td>
<td style="text-align:right;">
1534322
</td>
<td style="text-align:right;">
1566590
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1566590
</td>
<td style="text-align:right;">
1566590
</td>
</tr>
<tr>
<td style="text-align:right;">
494
</td>
<td style="text-align:right;">
1235582
</td>
<td style="text-align:right;">
1441176
</td>
<td style="text-align:right;">
1720674
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1720674
</td>
<td style="text-align:right;">
1720674
</td>
</tr>
<tr>
<td style="text-align:right;">
591
</td>
<td style="text-align:right;">
1218996
</td>
<td style="text-align:right;">
1108168
</td>
<td style="text-align:right;">
1542916
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1542916
</td>
<td style="text-align:right;">
1542916
</td>
</tr>
<tr>
<td style="text-align:right;">
645
</td>
<td style="text-align:right;">
1217311
</td>
<td style="text-align:right;">
1504604
</td>
<td style="text-align:right;">
1586612
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1586612
</td>
<td style="text-align:right;">
1586612
</td>
</tr>
<tr>
<td style="text-align:right;">
735
</td>
<td style="text-align:right;">
1192570
</td>
<td style="text-align:right;">
1537154
</td>
<td style="text-align:right;">
1379873
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
1537154
</td>
<td style="text-align:right;">
1379873
</td>
</tr>
<tr>
<td style="text-align:right;">
807
</td>
<td style="text-align:right;">
1213061
</td>
<td style="text-align:right;">
1420991
</td>
<td style="text-align:right;">
1359655
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
1420991
</td>
<td style="text-align:right;">
1359655
</td>
</tr>
<tr>
<td style="text-align:right;">
860
</td>
<td style="text-align:right;">
1209484
</td>
<td style="text-align:right;">
1345773
</td>
<td style="text-align:right;">
1503219
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1503219
</td>
<td style="text-align:right;">
1503219
</td>
</tr>
<tr>
<td style="text-align:right;">
995
</td>
<td style="text-align:right;">
1197708
</td>
<td style="text-align:right;">
1495210
</td>
<td style="text-align:right;">
1518871
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1518871
</td>
<td style="text-align:right;">
1518871
</td>
</tr>
</tbody>
</table>
<p><br> To calculate EVPI, we average NMBs given current information and NMBs given perfect information across simulation draws.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>enmbpi &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/mean">mean</a></span>(nmb_dt<span class="op">$</span>nmbpi)</span>
<span id="cb13-2"><a href="#cb13-2"></a>enmbci &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/mean">mean</a></span>(nmb_dt<span class="op">$</span>nmbci)</span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(enmbpi)</span></code></pre></div>
<pre><code>## [1] 1565713</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(enmbci)</span></code></pre></div>
<pre><code>## [1] 1537018</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(enmbpi <span class="op">-</span><span class="st"> </span>enmbci)</span></code></pre></div>
<pre><code>## [1] 28695</code></pre>
<p>The <code>icea</code> function performs this same calculation across all simulation draws from the PSA and for a number of values of willingness to pay values <span class="math inline">\(k\)</span>. A plot by group of the the EVPI for different values of <span class="math inline">\(k\)</span> is shown below. The kinks in the plot represent values of <span class="math inline">\(k\)</span> where the optimal strategy changes.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>ggplot2<span class="op">::</span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(icea<span class="op">$</span>evpi, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> evpi)) <span class="op">+</span></span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="op">~</span>grp) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"Willingness to pay"</span>) <span class="op">+</span></span>
<span id="cb19-3"><a href="#cb19-3"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"Expected value of perfect information"</span>) <span class="op">+</span></span>
<span id="cb19-4"><a href="#cb19-4"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> scales<span class="op">::</span>dollar) <span class="op">+</span></span>
<span id="cb19-5"><a href="#cb19-5"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span>(<span class="dt">label =</span> scales<span class="op">::</span>dollar) <span class="op">+</span></span>
<span id="cb19-6"><a href="#cb19-6"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) </span></code></pre></div>
<p><img src="icea_files/figure-html/evpi_plot-1.png" width="672"></p>
<p>We might also be interested in aggregating across subgroups. In particular, the total EVPI can be calculated as a weighted average of the group specific EVPIs,</p>
<p><span class="math display">\[
\begin{aligned}
totEVPI &amp;= \sum_{g=1}^{G} w_g EVPI_g,
\end{aligned}
\]</span> where <span class="math inline">\(w_g \in (0, 1)\)</span> is a weight denoting that proportion of the population represented by subgroup <span class="math inline">\(g\)</span> and <span class="math inline">\(\sum_{g=1}^{G} w_g = 1\)</span>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>w_dt &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/data.table">data.table</a></span>(<span class="dt">grp =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste0</a></span>(<span class="st">"Group "</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">1</span>, <span class="dv">2</span>)), <span class="dt">w =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="fl">0.25</span>, <span class="fl">.75</span>))</span>
<span id="cb20-2"><a href="#cb20-2"></a>evpi &lt;-<span class="st"> </span>icea<span class="op">$</span>evpi</span>
<span id="cb20-3"><a href="#cb20-3"></a>evpi &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/merge">merge</a></span>(evpi, w_dt, <span class="dt">by =</span> <span class="st">"grp"</span>)</span>
<span id="cb20-4"><a href="#cb20-4"></a>totevpi &lt;-<span class="st"> </span>evpi[,<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">lapply</a></span>(.SD, weighted.mean, <span class="dt">w =</span> w),</span>
<span id="cb20-5"><a href="#cb20-5"></a>                by =<span class="st"> "k"</span>, .SDcols =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"evpi"</span>)]</span>
<span id="cb20-6"><a href="#cb20-6"></a>ggplot2<span class="op">::</span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(totevpi, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> evpi)) <span class="op">+</span></span>
<span id="cb20-7"><a href="#cb20-7"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"Willingness to pay"</span>) <span class="op">+</span></span>
<span id="cb20-8"><a href="#cb20-8"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"Total EVPI"</span>) <span class="op">+</span></span>
<span id="cb20-9"><a href="#cb20-9"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> scales<span class="op">::</span>dollar) <span class="op">+</span></span>
<span id="cb20-10"><a href="#cb20-10"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span>(<span class="dt">label =</span> scales<span class="op">::</span>dollar) <span class="op">+</span></span>
<span id="cb20-11"><a href="#cb20-11"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) </span></code></pre></div>
<p><img src="icea_files/figure-html/totevpi-1.png" width="672"></p>
</div>
<div id="distribution-of-health-and-cost-outcomes" class="section level2">
<h2 class="hasAnchor">
<a href="#distribution-of-health-and-cost-outcomes" class="anchor"></a><span class="header-section-number">3.4</span> Distribution of health and cost outcomes</h2>
<p><code>icea</code> produces means, 2.5% quantiles, and 97.5% quantiles for costs and efficacy.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(icea<span class="op">$</span>summary)</span></code></pre></div>
<pre><code>##      strategy     grp    e_mean  e_lower   e_upper       c_mean
## 1: Strategy 1 Group 1  8.004532 7.625347  8.399756     7.427476
## 2: Strategy 2 Group 1 10.055709 8.448506 11.642793 60586.499697
## 3: Strategy 3 Group 1  8.510334 7.332195  9.708251 60757.113334
## 4: Strategy 1 Group 2  8.002205 7.597320  8.371528     7.368609
## 5: Strategy 2 Group 2 10.467755 8.851752 11.956592 60696.563802
## 6: Strategy 3 Group 2 11.000691 9.725894 12.131825 60733.750804
##         c_lower      c_upper
## 1:     6.134231     9.034617
## 2: 45176.893995 80647.903901
## 3: 44415.464271 79251.737042
## 4:     6.135822     8.885084
## 5: 44094.863030 80046.703058
## 6: 44985.051180 82950.291507</code></pre>
<p>Other summary statistics can be computed using R packages such as <code>data.table</code>.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a>ce[, .(<span class="dt">median_cost =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/median">median</a></span>(cost), <span class="dt">median_qalys =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/median">median</a></span>(qalys)),</span>
<span id="cb23-2"><a href="#cb23-2"></a>   by =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"strategy"</span>, <span class="st">"grp"</span>)]</span></code></pre></div>
<pre><code>##      strategy     grp  median_cost median_qalys
## 1: Strategy 1 Group 1     7.389074     8.007106
## 2: Strategy 1 Group 2     7.336006     8.007338
## 3: Strategy 2 Group 1 59631.933760    10.046966
## 4: Strategy 2 Group 2 60164.995846    10.462405
## 5: Strategy 3 Group 1 60437.497004     8.504607
## 6: Strategy 3 Group 2 59557.552101    11.006864</code></pre>
</div>
<div id="cost-effectiveness-plane" class="section level2">
<h2 class="hasAnchor">
<a href="#cost-effectiveness-plane" class="anchor"></a><span class="header-section-number">3.5</span> Cost-effectiveness plane</h2>
<p>The cost-effectiveness plane plots the incremental effectiveness of a treatment strategy (relative to a comparator) against the incremental cost of the treatment strategy. The plot is useful because it demonstrates both the uncertainty and the magnitude of the estimates. Each point on the plot is from a particular random draw from the PSA.</p>
<p>Data for plotting a cost-effectiveness plane comes from the <code>delta</code> output generated from the <code>icea_pw</code> function, which, for each sampled parameter set and treatment strategy, estimates differences in costs, effectiveness, and any other variables specified in <code>custom_vars</code>relative to the comparator. The dotted line in the plot is the willingness to pay line, with slope equal to the value of <span class="math inline">\(k\)</span>. For a given <span class="math inline">\(k\)</span>, points below the line are cost-effective while those above it are not.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(icea_pw<span class="op">$</span>delta)</span></code></pre></div>
<pre><code>##    sample   strategy     grp       ie       ic
## 1:      1 Strategy 2 Group 1 1.497467 57687.97
## 2:      2 Strategy 2 Group 1 1.428877 65857.23
## 3:      3 Strategy 2 Group 1 3.184584 44830.68
## 4:      4 Strategy 2 Group 1 1.475885 64228.60
## 5:      5 Strategy 2 Group 1 1.045039 58613.55
## 6:      6 Strategy 2 Group 1 1.303221 45173.35</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Extremes">max</a></span>(icea_pw<span class="op">$</span>delta[, ic]) <span class="op">*</span><span class="st"> </span><span class="fl">1.1</span></span>
<span id="cb27-2"><a href="#cb27-2"></a>xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Round">ceiling</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Extremes">max</a></span>(icea_pw<span class="op">$</span>delta[, ie]) <span class="op">*</span><span class="st"> </span><span class="fl">1.1</span>)</span>
<span id="cb27-3"><a href="#cb27-3"></a>ggplot2<span class="op">::</span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(icea_pw<span class="op">$</span>delta, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> ie, <span class="dt">y =</span> ic, <span class="dt">col =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(strategy))) <span class="op">+</span><span class="st"> </span></span>
<span id="cb27-4"><a href="#cb27-4"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span>(<span class="dt">size =</span> <span class="fl">.5</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="op">~</span>grp) <span class="op">+</span><span class="st"> </span></span>
<span id="cb27-5"><a href="#cb27-5"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"Incremental QALYs"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"Incremental cost"</span>) <span class="op">+</span></span>
<span id="cb27-6"><a href="#cb27-6"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span>(<span class="dt">label =</span> dollar, <span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span>ylim, ylim)) <span class="op">+</span></span>
<span id="cb27-7"><a href="#cb27-7"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span>(<span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span>xlim, xlim), <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="op">-</span><span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">2</span>)) <span class="op">+</span></span>
<span id="cb27-8"><a href="#cb27-8"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Strategy"</span>) <span class="op">+</span></span>
<span id="cb27-9"><a href="#cb27-9"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span>(<span class="dt">slope =</span> <span class="dv">150000</span>, <span class="dt">linetype =</span> <span class="st">"dashed"</span>) <span class="op">+</span></span>
<span id="cb27-10"><a href="#cb27-10"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span>(<span class="dt">xintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
<p><img src="icea_files/figure-html/ceplane_plot-1.png" width="672"></p>
</div>
<div id="cost-effectiveness-acceptability-curve-ceac" class="section level2">
<h2 class="hasAnchor">
<a href="#cost-effectiveness-acceptability-curve-ceac" class="anchor"></a><span class="header-section-number">3.6</span> Cost-effectiveness acceptability curve (CEAC)</h2>
<p>The cost-effectiveness acceptability curve (CEAC) is similar to the MCE plot. The difference is that the CEAC compares each strategy to a single comparator whereas the MCE plot considers all strategies simultaneously. Output to produce a CEAC is generated from the <code>icea_pw</code> function.</p>
<p>The plot shows that, in subgroup 1, Strategy 2 has larger NMBs than Strategy 1 with very high probability for reasonable values of <span class="math inline">\(k\)</span>. Strategy 3 also has higher NMBs than Strategy 1 with probability over 1/2 for values of <span class="math inline">\(k\)</span> larger than 120,500. In group 2, both Strategy 2 and Strategy 3 have higher NMBs than Strategy 1 for almost all values of <span class="math inline">\(k\)</span>, although this probability is larger for Strategy 2 than Strategy 3 when <span class="math inline">\(k\)</span> is smaller.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>ggplot2<span class="op">::</span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(icea_pw<span class="op">$</span>ceac, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> prob, <span class="dt">col =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(strategy))) <span class="op">+</span></span>
<span id="cb28-2"><a href="#cb28-2"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="op">~</span>grp) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"Willingness to pay"</span>) <span class="op">+</span></span>
<span id="cb28-3"><a href="#cb28-3"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"Probability most cost-effective"</span>) <span class="op">+</span></span>
<span id="cb28-4"><a href="#cb28-4"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> scales<span class="op">::</span>dollar) <span class="op">+</span></span>
<span id="cb28-5"><a href="#cb28-5"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Strategy"</span>)</span></code></pre></div>
<p><img src="icea_files/figure-html/ceac_plot-1.png" width="672"></p>
</div>
<div id="credible-intervals-for-incremental-costs-and-effectiveness" class="section level2">
<h2 class="hasAnchor">
<a href="#credible-intervals-for-incremental-costs-and-effectiveness" class="anchor"></a><span class="header-section-number">3.7</span> Credible intervals for incremental costs and effectiveness</h2>
<p>Similar to the <code>icea</code> function, <code>icea_pw</code> produces means, 2.5% quantiles, and 97.5% quantiles for incremental costs and incremental efficacy. The table also contains the ICER, which is equal to expected incremental costs divided by the measure of expected incremental efficacy.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(icea_pw<span class="op">$</span>summary)</span></code></pre></div>
<pre><code>##      strategy     grp   ie_mean   ie_lower ie_upper  ic_mean ic_lower
## 1: Strategy 2 Group 1 2.0511771  0.4379639 3.683574 60579.07 45169.67
## 2: Strategy 3 Group 1 0.5058018 -0.7506895 1.718309 60749.69 44408.40
## 3: Strategy 2 Group 2 2.4655507  0.8324790 4.060741 60689.20 44087.87
## 4: Strategy 3 Group 2 2.9984860  1.7366178 4.187179 60726.38 44977.75
##    ic_upper      icer
## 1: 80640.24  29533.81
## 2: 79245.04 120105.71
## 3: 80039.84  24614.86
## 4: 82942.89  20252.35</code></pre>
<p>Again similar to the <code>icea</code> function, the user can also estimate incremental effects for outcome variables not included in the summary table.</p>
</div>
</div>
<div id="value-of-individualized-care" class="section level1">
<h1 class="hasAnchor">
<a href="#value-of-individualized-care" class="anchor"></a><span class="header-section-number">4</span> Value of individualized care</h1>
<p>The previous analyses allow NMBs and optimal treatment decisions to vary by subgroup. In contrast, most CEAs estimate the treatment, <span class="math inline">\(j^{*}\)</span>, that is optimal when averaging NMBs over the entire population. In particular, if the population is broken up into <span class="math inline">\(G\)</span> distinct subgroups, the optimal treatment is given by,</p>
<p><span class="math display">\[
\begin{aligned}
j^{*} = \text{argmax}_j \sum_{g=1}^{G} w_g E_{\theta}\left[NMB_g(j,\theta)\right].
\end{aligned}
\]</span></p>
<p><span class="citation">Basu and Meltzer (2007)</span> have shown that selecting subgroup specific treatments increases expected net benefits relative to this one-size fits all approach. They refer to additional net benefit as the expected value of individualized care (EPIC), which can be computed in terms of NMBs using the subgroup approach illustrated here as,</p>
<p><span class="math display">\[
\begin{aligned}
\sum_{g=1}^G w_g E_{\theta}\left[NMB_g(j^{*}_s,\theta)\right] - \sum_{g=1}^G w_g  E_{\theta}\left[NMB_g(j^{*},\theta)\right].
\end{aligned}
\]</span></p>
<p>We can estimate the value of individualized care as follows:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Compute total expected NMB with one-size fits all treatment</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>ce &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/merge">merge</a></span>(ce, w_dt, <span class="dt">by =</span> <span class="st">"grp"</span>)</span>
<span id="cb31-3"><a href="#cb31-3"></a>totenmb &lt;-<span class="st"> </span>ce[, .(<span class="dt">totenmb =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/weighted.mean">weighted.mean</a></span>(nmb, <span class="dt">w =</span> w)), by =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"strategy"</span>)]</span>
<span id="cb31-4"><a href="#cb31-4"></a>totenmb_max &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Extremes">max</a></span>(totenmb<span class="op">$</span>totenmb)</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="co"># Compute total expected NMB with individualized treatment</span></span>
<span id="cb32-2"><a href="#cb32-2"></a>itotenmb_grp_max &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/apply">apply</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/data.table/topics/as.matrix">as.matrix</a></span>(enmb[, <span class="dv">-1</span>]), <span class="dv">2</span>, max)</span>
<span id="cb32-3"><a href="#cb32-3"></a>itotenmb_max &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(itotenmb_grp_max <span class="op">*</span><span class="st"> </span>w_dt<span class="op">$</span>w)</span></code></pre></div>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># Compute EVIC</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>totnmb_scenarios &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(itotenmb_max, totenmb_max)</span>
<span id="cb33-3"><a href="#cb33-3"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(totnmb_scenarios) &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"Individualized total expected NMB"</span>,</span>
<span id="cb33-4"><a href="#cb33-4"></a>                              <span class="st">"One-size fits all total expected NMB"</span>)</span>
<span id="cb33-5"><a href="#cb33-5"></a>evic &lt;-<span class="st"> </span>totnmb_scenarios[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>totnmb_scenarios[<span class="dv">2</span>]</span>
<span id="cb33-6"><a href="#cb33-6"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(evic) &lt;-<span class="st"> "EVIC"</span></span>
<span id="cb33-7"><a href="#cb33-7"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(evic)</span></code></pre></div>
<pre><code>##     EVIC 
## 57994.23</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(evic<span class="op">/</span><span class="dv">150000</span>)</span></code></pre></div>
<pre><code>##      EVIC 
## 0.3866282</code></pre>
<p>Our estimate of the EVIC is $57,994, or in terms of net health benefits, 0.387 QALYs.</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-baio2012bayesian">
<p>Baio, Gianluca. 2012. <em>Bayesian Methods in Health Economics</em>. CRC Press.</p>
</div>
<div id="ref-baio2015probabilistic">
<p>Baio, Gianluca, and A Philip Dawid. 2015. “Probabilistic Sensitivity Analysis in Health Economics.” <em>Statistical Methods in Medical Research</em> 24 (6): 615–34.</p>
</div>
<div id="ref-barton2008optimal">
<p>Barton, Garry R, Andrew H Briggs, and Elisabeth AL Fenwick. 2008. “Optimal Cost-Effectiveness Decisions: The Role of the Cost-Effectiveness Acceptability Curve (Ceac), the Cost-Effectiveness Acceptability Frontier (Ceaf), and the Expected Value of Perfection Information (Evpi).” <em>Value in Health</em> 11 (5): 886–97.</p>
</div>
<div id="ref-basu2007value">
<p>Basu, Anirban, and David Meltzer. 2007. “Value of Information on Preference Heterogeneity and Individualized Care.” <em>Medical Decision Making</em> 27 (2): 112–27.</p>
</div>
<div id="ref-espinoza2014value">
<p>Espinoza, Manuel A, Andrea Manca, Karl Claxton, and Mark J Sculpher. 2014. “The Value of Heterogeneity for Cost-Effectiveness Subgroup Analysis: Conceptual Framework and Application.” <em>Medical Decision Making</em> 34 (8): 951–64.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#overview"><span class="toc-section-number">1</span> Overview</a></li>
      <li><a href="#net-monetary-benefits"><span class="toc-section-number">2</span> Net monetary benefits</a></li>
      <li>
<a href="#probabilistic-sensitivity-analysis"><span class="toc-section-number">3</span> Probabilistic sensitivity analysis</a><ul class="nav nav-pills nav-stacked">
<li><a href="#probability-most-cost-effective"><span class="toc-section-number">3.1</span> Probability most cost-effective</a></li>
      <li><a href="#cost-effectiveness-acceptability-frontier-ceaf"><span class="toc-section-number">3.2</span> Cost-effectiveness acceptability frontier (CEAF)</a></li>
      <li><a href="#value-of-perfect-information"><span class="toc-section-number">3.3</span> Value of perfect information</a></li>
      <li><a href="#distribution-of-health-and-cost-outcomes"><span class="toc-section-number">3.4</span> Distribution of health and cost outcomes</a></li>
      <li><a href="#cost-effectiveness-plane"><span class="toc-section-number">3.5</span> Cost-effectiveness plane</a></li>
      <li><a href="#cost-effectiveness-acceptability-curve-ceac"><span class="toc-section-number">3.6</span> Cost-effectiveness acceptability curve (CEAC)</a></li>
      <li><a href="#credible-intervals-for-incremental-costs-and-effectiveness"><span class="toc-section-number">3.7</span> Credible intervals for incremental costs and effectiveness</a></li>
      </ul>
</li>
      <li><a href="#value-of-individualized-care"><span class="toc-section-number">4</span> Value of individualized care</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Devin Incerti, Jeroen P. Jansen.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
