<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Individualized cost-effectiveness analysis (iCEA) • hesim</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/simplex/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">hesim</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/cea-vignette.html">Individualized cost-effectiveness analysis</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/dincerti/hesim">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>Individualized cost-effectiveness analysis (iCEA)</h1>
                        <h4 class="author">Devin Incerti</h4>
            
            <h4 class="date">2017-09-19</h4>
          </div>

    
    
<div class="contents">
<div id="overview" class="section level1">
<h1 class="hasAnchor">
<a href="#overview" class="anchor"></a>Overview</h1>
<p>Individualized cost-effectiveness analysis (iCEA) evaluates the cost-effectiveness of treatments at the individual (or subgroup) level. This has two major implications:</p>
<ul>
<li>Optimal treatments will vary across patients.</li>
<li>Treatments will be more cost-effective for some patients than others.</li>
</ul>
<p>The <code>hesim</code> package help facilitate iCEA by providing a number of functions for analyzing subgroup level health and cost outcomes from simulation models that quantify parameter uncertainty using probabilistic sensitivity analysis (PSA). These functions take simulation output and generate measures commonly used for technology assessment including:</p>
<ul>
<li>net monetary benefits (NMBs).</li>
<li>incremental cost-effectiveness ratios (ICERs).</li>
<li>cost-effectiveness acceptability curves (CEACs).</li>
<li>the expected value of perfect information (EVPI).</li>
</ul>
<p>The rest of this document provides an overview of iCEA and how it can be conducted using <code>hesim</code>. The perspective is Bayesian in nature in that it is concerned with estimating the entire distribution of outcomes rather than just expected values <span class="citation">(Baio 2012; Baio and Dawid 2015)</span>. It also stresses that both optimal treatments and the cost-effectiveness of those treatments vary across individuals <span class="citation">(Basu and Meltzer 2007; Espinoza et al. 2014)</span>.</p>
</div>
<div id="net-monetary-benefits" class="section level1">
<h1 class="hasAnchor">
<a href="#net-monetary-benefits" class="anchor"></a>Net monetary benefits</h1>
<p>Decision analysis provides a formal framework for making treatment decisions based on the utility that a therapy provides to a patient population. Decisions are typically made using a net benefit approach grounded in expected utility theory. The optimal treatment arm is the one that maximizes expected NMBs where expected NMBs are calculated by averaging over the patient population and uncertain parameters <span class="math inline">\(\theta\)</span>. For a given subgroup <span class="math inline">\(g\)</span> and parameter set <span class="math inline">\(\theta\)</span>, NMBs are computed as the difference between the monetized health gains from an intervention less costs, or,</p>
<p><span class="math display">\[
\begin{aligned}
NMB_g(j,\theta) = e_{gj}\cdot k- c_{gj},
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(e_{gj}\)</span> and <span class="math inline">\(c_{gj}\)</span> are measures of clinical effectiveness (e.g. QALYs) and costs in subgroup <span class="math inline">\(g\)</span> using treatment <span class="math inline">\(j\)</span> respectively, and <span class="math inline">\(k\)</span> is a decision makers willingness to pay per unit of clinical effectiveness. The optimal treatment for a given subgroup is the one that maximizes expected NMBs,</p>
<p><span class="math display">\[
\begin{aligned}
j^{*}_g = \text{argmax}_j E_{\theta} \left[NMB_g(j,\theta)\right].
\end{aligned}
\]</span></p>
<p>In practice, new interventions are usually compared to a standard treatment often referred to as the comparator. In these cases, a new treatment in a given subgroup is preferred to the comparator if the expected incremental net monetary benefit (INMB) of the new treatment is positive; that is, treatment 1 is preferred to treatment 0 in subgroup <span class="math inline">\(g\)</span> if <span class="math inline">\(E_\theta \left[INMB_g\right] &gt; 0\)</span> where the INMB in a particular subgroup is given by</p>
<p><span class="math display">\[
\begin{aligned}
INMB_g(\theta) = NMB_g(j = 1, \theta) - NMB_g(j = 0, \theta).
\end{aligned}
\]</span> Equivalently, treatment <span class="math inline">\(1\)</span> is preferred to treatment <span class="math inline">\(0\)</span> in subgroup <span class="math inline">\(g\)</span> if the incremental cost-effectiveness ratio (ICER) is greater than the willingness to pay threshold <span class="math inline">\(k\)</span>,</p>
<p><span class="math display">\[
\begin{aligned}
k &gt; \frac{c_{g1} - c_{s0}}{e_{g1} - e_{g0}} = ICER_g.
\end{aligned}
\]</span></p>
</div>
<div id="probabilistic-sensitivity-analysis" class="section level1">
<h1 class="hasAnchor">
<a href="#probabilistic-sensitivity-analysis" class="anchor"></a>Probabilistic sensitivity analysis</h1>
<p>Expected NMBs are expected values and ignore parameter uncertainty. This implies that NMBs are uncertain and that optimal treatment arms may be selected incorrectly. This uncertainty can be quantified using PSA, which uses Bayesian and quasi-Bayesian techniques to estimate the distribution of NMBs given the distribution of the parameters for each treatment arm.</p>
<p>Since the joint distribution of the model parameters cannot be derived analytically (except in the simplest cases), the distribution of <span class="math inline">\(\theta\)</span> is approximated by simulating the parameters from their joint posterior distribution and calculating relevant quantities of interest as a function of the simulated parameters. For each treatment arm and subgroup, PSA therefore produces <span class="math inline">\(n\)</span> random draws from the posterior distribution of clinical effectiveness and costs,</p>
<p><span class="math display">\[
\begin{aligned}
e_{gj} &amp;= [e_{gj}^1, e_{gj}^2, \dots, e_{gj}^n] \\
c_{gj} &amp;= [c_{gj}^1, c_{gj}^2, \dots, c_{gj}^n].
\end{aligned}
\]</span></p>
<p>Below we simulate costs and QALYs for three treatment arms and two subgroups (in a real world analysis, this output would be derived from a detailed health-economic simulation model). Arm 1 is the current standard of care; it is the cheapest therapy, but also the least efficacious. Arms 2 and 3 are equally costly, but Arm 2 is more effective in subgroup 1 while Arm 3 is more effective in subgroup 2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nsims &lt;-<span class="st"> </span><span class="dv">1000</span>

<span class="co"># cost</span>
c &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">mode =</span> <span class="st">"list"</span>, <span class="dt">length =</span> <span class="dv">6</span>)
<span class="kw">names</span>(c) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">"Arm 1, Grp 1"</span>, <span class="st">"Arm 1, Grp 2"</span>, <span class="st">"Arm 2, Grp 1"</span>,
              <span class="st">"Arm 2, Grp 2"</span>, <span class="st">"Arm 3, Grp 1"</span>, <span class="st">"Arm 3, Grp 2"</span>)
c[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">rlnorm</span>(nsims, <span class="dv">2</span>, .<span class="dv">1</span>)
c[[<span class="dv">2</span>]] &lt;-<span class="st"> </span><span class="kw">rlnorm</span>(nsims, <span class="dv">2</span>, .<span class="dv">1</span>)
c[[<span class="dv">3</span>]] &lt;-<span class="st"> </span><span class="kw">rlnorm</span>(nsims, <span class="dv">11</span>, .<span class="dv">15</span>)
c[[<span class="dv">4</span>]] &lt;-<span class="st"> </span><span class="kw">rlnorm</span>(nsims, <span class="dv">11</span>, .<span class="dv">15</span>)
c[[<span class="dv">5</span>]] &lt;-<span class="st"> </span><span class="kw">rlnorm</span>(nsims, <span class="dv">11</span>, .<span class="dv">15</span>)
c[[<span class="dv">6</span>]] &lt;-<span class="st"> </span><span class="kw">rlnorm</span>(nsims, <span class="dv">11</span>, .<span class="dv">15</span>)

<span class="co"># effectiveness</span>
e &lt;-<span class="st"> </span>c
e[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">rnorm</span>(nsims, <span class="dv">8</span>, .<span class="dv">2</span>)
e[[<span class="dv">2</span>]] &lt;-<span class="st"> </span><span class="kw">rnorm</span>(nsims, <span class="dv">8</span>, .<span class="dv">2</span>)
e[[<span class="dv">3</span>]] &lt;-<span class="st"> </span><span class="kw">rnorm</span>(nsims, <span class="dv">10</span>, .<span class="dv">8</span>)
e[[<span class="dv">4</span>]] &lt;-<span class="st"> </span><span class="kw">rnorm</span>(nsims, <span class="fl">10.5</span>, .<span class="dv">8</span>)
e[[<span class="dv">5</span>]] &lt;-<span class="st"> </span><span class="kw">rnorm</span>(nsims, <span class="fl">8.5</span>, .<span class="dv">6</span>)
e[[<span class="dv">6</span>]] &lt;-<span class="st"> </span><span class="kw">rnorm</span>(nsims, <span class="dv">11</span>, .<span class="dv">6</span>)

<span class="co"># cost and effectiveness by arm and simulation</span>
<span class="kw">library</span>(<span class="st">"data.table"</span>)
ce &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/data.table/topics/data.table">data.table</a></span>(<span class="dt">sim =</span> <span class="kw">rep</span>(<span class="kw">seq</span>(nsims), <span class="kw">length</span>(e)),
                             <span class="dt">arm =</span> <span class="kw">rep</span>(<span class="kw">paste0</span>(<span class="st">"Arm "</span>, <span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">3</span>)), 
                                       <span class="dt">each =</span> nsims *<span class="st"> </span><span class="dv">2</span>),
                             <span class="dt">grp =</span> <span class="kw">rep</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">"Group 1"</span>, <span class="st">"Group 2"</span>),
                                           <span class="dt">each =</span> nsims), <span class="dv">3</span>),
                             <span class="dt">cost =</span> <span class="kw">do.call</span>(<span class="st">"c"</span>, c), <span class="dt">qalys =</span> <span class="kw">do.call</span>(<span class="st">"c"</span>, e))
<span class="kw">head</span>(ce)</code></pre></div>
<pre><code>##    sim   arm     grp     cost    qalys
## 1:   1 Arm 1 Group 1 7.845147 8.491794
## 2:   2 Arm 1 Group 1 8.045799 8.092606
## 3:   3 Arm 1 Group 1 6.911296 8.441434
## 4:   4 Arm 1 Group 1 7.954867 8.370473
## 5:   5 Arm 1 Group 1 7.094071 8.116965
## 6:   6 Arm 1 Group 1 7.658935 7.698646</code></pre>
<p>For any given willingness to pay <span class="math inline">\(k\)</span>, expected NMBs can be calculated by arm, subgroup, and simulation number. For example, with <span class="math inline">\(k=150,000\)</span>, a reasonable estimate of the value of a life-year in the United States, Arm 2 provides the highest expected NMBs in subgroup 2 while Arm 3 provides the highest expected NMBs in subgroup 2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ce &lt;-<span class="st"> </span>ce[, nmb :<span class="er">=</span><span class="st"> </span><span class="dv">150000</span> *<span class="st"> </span>qalys -<span class="st"> </span>cost]
enmb &lt;-<span class="st"> </span>ce[, .(<span class="dt">enmb =</span> <span class="kw">mean</span>(nmb)), by =<span class="st"> </span><span class="kw">c</span>(<span class="st">"arm"</span>, <span class="st">"grp"</span>)]
enmb &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/data.table/topics/dcast.data.table">dcast</a></span>(enmb, arm ~<span class="st"> </span>grp, <span class="dt">value.var =</span> <span class="st">"enmb"</span>)
<span class="kw">print</span>(enmb)</code></pre></div>
<pre><code>##      arm Group 1 Group 2
## 1: Arm 1 1200630 1201978
## 2: Arm 2 1430187 1514951
## 3: Arm 3 1209150 1589661</code></pre>
<p>A number of measures have been proposed in the health economics literature to summarize the PSA. Below we describe the most common measures, which can be calculated using the functions <code>icea</code> and <code>icea_pw</code>. The <code>icea</code> function summarizes results by taking into account each treatment arm in the analysis, while the function <code>icea_pw</code> summarizes “pairwise” results in which each treatment is compared to a comparator.</p>
<p>We can use the <code>icea</code> function to summarize results from our <code>data.table</code> object of simulated output for a range of willingness to pay values,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">"hesim"</span>)
ktop &lt;-<span class="st"> </span><span class="dv">200000</span>
icea.dt &lt;-<span class="st">  </span><span class="kw"><a href="../reference/icea.html">icea</a></span>(ce, <span class="dt">k =</span> <span class="kw">seq</span>(<span class="dv">0</span>, ktop, <span class="dv">500</span>), <span class="dt">sim =</span> <span class="st">"sim"</span>, <span class="dt">arm =</span> <span class="st">"arm"</span>,
              <span class="dt">grp =</span> <span class="st">"grp"</span>, <span class="dt">e =</span> <span class="st">"qalys"</span>, <span class="dt">c =</span> <span class="st">"cost"</span>)</code></pre></div>
<p>The most important input in <code>icea</code> is the <code>data.table</code> object (<code>x</code>) containing columns for simulation number (<code>sim</code>), treatment arm (<code>arm</code>), subgroup (<code>grp</code>), clinical effectiveness (<code>e</code>), and costs (<code>c</code>). Users specify the names of the relevant columns in their output table as strings. The other relevant parameter is <span class="math inline">\(k\)</span>, which is a range of willingness to pay values to use for estimating NMBs.</p>
<p>Likewise, we can use <code>icea_pw</code> to summarize the PSA when directly comparing the two treatment arms (Arm 2 and Arm 3) to the comparator (Arm 1).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">icea.pw.dt &lt;-<span class="st">  </span><span class="kw"><a href="../reference/icea.html">icea_pw</a></span>(ce,  <span class="dt">k =</span> <span class="kw">seq</span>(<span class="dv">0</span>, ktop, <span class="dv">500</span>), <span class="dt">control =</span> <span class="st">"Arm 1"</span>,
                     <span class="dt">sim =</span> <span class="st">"sim"</span>, <span class="dt">arm =</span> <span class="st">"arm"</span>, <span class="dt">e =</span> <span class="st">"qalys"</span>, <span class="dt">c =</span> <span class="st">"cost"</span>)</code></pre></div>
<p>The same inputs are used as in <code>icea</code> except users must specify the name of the control arm.</p>
<div id="probability-most-cost-effective" class="section level2">
<h2 class="hasAnchor">
<a href="#probability-most-cost-effective" class="anchor"></a>Probability most cost-effective</h2>
<p>A useful summary measure for quantifying uncertainty is the probability that each treatment arm is the most cost effective. For a particular subgroup, this is estimated from simulation output as the proportion of simulation draws that each arm has the highest NMB. For example, consider a random sample of 10 draws from the PSA simulation output and suppose <span class="math inline">\(k\)</span> is again equal to <span class="math inline">\(150,000\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">"knitr"</span>)
ce.nmb &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/data.table/topics/dcast.data.table">dcast</a></span>(ce[sim %in%<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span>:nsims, <span class="dv">10</span>) &amp;<span class="st"> </span>grp ==<span class="st"> "Group 2"</span>], 
               sim ~<span class="st"> </span>arm, <span class="dt">value.var =</span> <span class="st">"nmb"</span>)
<span class="kw"><a href="http://www.rdocumentation.org/packages/data.table/topics/setattr">setnames</a></span>(ce.nmb, <span class="kw">colnames</span>(ce.nmb), <span class="kw">c</span>(<span class="st">"sim"</span>, <span class="st">"nmb1"</span>, <span class="st">"nmb2"</span>, <span class="st">"nmb3"</span>))
ce.nmb &lt;-<span class="st"> </span>ce.nmb[, maxj :<span class="er">=</span><span class="st"> </span><span class="kw">apply</span>(ce.nmb[, .(nmb1, nmb2, nmb3)], <span class="dv">1</span>, which.max)]
ce.nmb &lt;-<span class="st"> </span>ce.nmb[, maxj :<span class="er">=</span><span class="st"> </span><span class="kw">factor</span>(maxj, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))]</code></pre></div>
<table class="table">
<thead><tr>
<th style="text-align:right;">
sim
</th>
<th style="text-align:right;">
nmb1
</th>
<th style="text-align:right;">
nmb2
</th>
<th style="text-align:right;">
nmb3
</th>
<th style="text-align:left;">
maxj
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
1190403
</td>
<td style="text-align:right;">
1507166
</td>
<td style="text-align:right;">
1447674
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
207
</td>
<td style="text-align:right;">
1210210
</td>
<td style="text-align:right;">
1428523
</td>
<td style="text-align:right;">
1437114
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
237
</td>
<td style="text-align:right;">
1219973
</td>
<td style="text-align:right;">
1698028
</td>
<td style="text-align:right;">
1348966
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
293
</td>
<td style="text-align:right;">
1187691
</td>
<td style="text-align:right;">
1368981
</td>
<td style="text-align:right;">
1666257
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
324
</td>
<td style="text-align:right;">
1226444
</td>
<td style="text-align:right;">
1489093
</td>
<td style="text-align:right;">
1567128
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
375
</td>
<td style="text-align:right;">
1187133
</td>
<td style="text-align:right;">
1467854
</td>
<td style="text-align:right;">
1565449
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
516
</td>
<td style="text-align:right;">
1175494
</td>
<td style="text-align:right;">
1563232
</td>
<td style="text-align:right;">
1587549
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
527
</td>
<td style="text-align:right;">
1196938
</td>
<td style="text-align:right;">
1603275
</td>
<td style="text-align:right;">
1662685
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
843
</td>
<td style="text-align:right;">
1262818
</td>
<td style="text-align:right;">
1334147
</td>
<td style="text-align:right;">
1559250
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
907
</td>
<td style="text-align:right;">
1212848
</td>
<td style="text-align:right;">
1418237
</td>
<td style="text-align:right;">
1557801
</td>
<td style="text-align:left;">
3
</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mce &lt;-<span class="st"> </span><span class="kw">prop.table</span>(<span class="kw">table</span>(ce.nmb$maxj))
<span class="kw">print</span>(mce)</code></pre></div>
<pre><code>## 
##   1   2   3 
## 0.0 0.2 0.8</code></pre>
<p>In this example, treatments 1, 2, and 3 have the highest NMBs a fraction 0, 0.2, and 0.8 of the time respectively. The <code>icea</code> function performs this same calculations for a range of values of <span class="math inline">\(k\)</span> and all <code>nsims</code> random draws of the simulation output. The output is a tidy <code>data.table</code> which facilitates plotting with <code>ggplot</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">"ggplot2"</span>)
<span class="kw">library</span>(<span class="st">"scales"</span>)
<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme_get">theme_set</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggtheme">theme_bw</a></span>())
<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(icea.dt$mce, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> prob, <span class="dt">col =</span> <span class="kw">factor</span>(arm))) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_line</a></span>() +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/facet_wrap">facet_wrap</a></span>(~grp) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"Willingess to pay"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="st">"Probability most cost-effective"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> comma) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_hue">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Arm"</span>)</code></pre></div>
<p><img src="cea-vignette_files/figure-html/mce_plot-1.png" width="672"></p>
<p>In group 1, Arm 2 provides the greatest NMBs with high probability for almost all reasonable values of k. In group 2, the results are less certain, although Arm 3 provides the greatest NMBs with a higher probability than Arm 2.</p>
</div>
<div id="value-of-perfect-information" class="section level2">
<h2 class="hasAnchor">
<a href="#value-of-perfect-information" class="anchor"></a>Value of perfect information</h2>
<p>One draw back of the previous measure is that it ignores the magnitude of cost or QALY gains. A measure which combines the probability of being most effective with the magnitude of the expected NMB is the expected value of perfect information (EVPI). Intuitively, the EVPI provides an estimate of the amount that a decision maker would be willing to pay to collect additional data and completely eliminate uncertainty. Mathematically, the EVPI is defined as the difference between the maximum expected NMB given perfect information and the maximum expected NMB given current information. In other words, we calculate the NMB for the optimal treatment arm for each random draw of the parameters and compare that to the NMB for the treatment arm that is optimal when averaging across all parameters. Mathematically, the EVPI for subgroup <span class="math inline">\(g\)</span> is,</p>
<p><span class="math display">\[
\begin{aligned}
EVPI_g &amp;= E_\theta \left[max_j NMB_g(j, \theta)\right] - max_j E_\theta \left [ NMB_g(j, \theta)\right]. \\
\end{aligned}
\]</span></p>
<p>To illustrate consider the same random sample of 10 draws from our simulation output used above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">armmax.g2 &lt;-<span class="st"> </span><span class="kw">which.max</span>(enmb[[<span class="dv">3</span>]])
ce.nmb &lt;-<span class="st"> </span>ce.nmb[, nmbpi :<span class="er">=</span><span class="st"> </span><span class="kw">apply</span>(ce.nmb[, .(nmb1, nmb2, nmb3)], <span class="dv">1</span>, max)]
ce.nmb &lt;-<span class="st"> </span>ce.nmb[, nmbci :<span class="er">=</span><span class="st"> </span>ce.nmb[[armmax.g2 +<span class="st"> </span><span class="dv">1</span>]]]
<span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(ce.nmb, <span class="dt">digits =</span> <span class="dv">0</span>, <span class="dt">format =</span> <span class="st">"html"</span>)</code></pre></div>
<table class="table">
<thead><tr>
<th style="text-align:right;">
sim
</th>
<th style="text-align:right;">
nmb1
</th>
<th style="text-align:right;">
nmb2
</th>
<th style="text-align:right;">
nmb3
</th>
<th style="text-align:left;">
maxj
</th>
<th style="text-align:right;">
nmbpi
</th>
<th style="text-align:right;">
nmbci
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
1190403
</td>
<td style="text-align:right;">
1507166
</td>
<td style="text-align:right;">
1447674
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
1507166
</td>
<td style="text-align:right;">
1447674
</td>
</tr>
<tr>
<td style="text-align:right;">
207
</td>
<td style="text-align:right;">
1210210
</td>
<td style="text-align:right;">
1428523
</td>
<td style="text-align:right;">
1437114
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1437114
</td>
<td style="text-align:right;">
1437114
</td>
</tr>
<tr>
<td style="text-align:right;">
237
</td>
<td style="text-align:right;">
1219973
</td>
<td style="text-align:right;">
1698028
</td>
<td style="text-align:right;">
1348966
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
1698028
</td>
<td style="text-align:right;">
1348966
</td>
</tr>
<tr>
<td style="text-align:right;">
293
</td>
<td style="text-align:right;">
1187691
</td>
<td style="text-align:right;">
1368981
</td>
<td style="text-align:right;">
1666257
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1666257
</td>
<td style="text-align:right;">
1666257
</td>
</tr>
<tr>
<td style="text-align:right;">
324
</td>
<td style="text-align:right;">
1226444
</td>
<td style="text-align:right;">
1489093
</td>
<td style="text-align:right;">
1567128
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1567128
</td>
<td style="text-align:right;">
1567128
</td>
</tr>
<tr>
<td style="text-align:right;">
375
</td>
<td style="text-align:right;">
1187133
</td>
<td style="text-align:right;">
1467854
</td>
<td style="text-align:right;">
1565449
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1565449
</td>
<td style="text-align:right;">
1565449
</td>
</tr>
<tr>
<td style="text-align:right;">
516
</td>
<td style="text-align:right;">
1175494
</td>
<td style="text-align:right;">
1563232
</td>
<td style="text-align:right;">
1587549
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1587549
</td>
<td style="text-align:right;">
1587549
</td>
</tr>
<tr>
<td style="text-align:right;">
527
</td>
<td style="text-align:right;">
1196938
</td>
<td style="text-align:right;">
1603275
</td>
<td style="text-align:right;">
1662685
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1662685
</td>
<td style="text-align:right;">
1662685
</td>
</tr>
<tr>
<td style="text-align:right;">
843
</td>
<td style="text-align:right;">
1262818
</td>
<td style="text-align:right;">
1334147
</td>
<td style="text-align:right;">
1559250
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1559250
</td>
<td style="text-align:right;">
1559250
</td>
</tr>
<tr>
<td style="text-align:right;">
907
</td>
<td style="text-align:right;">
1212848
</td>
<td style="text-align:right;">
1418237
</td>
<td style="text-align:right;">
1557801
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1557801
</td>
<td style="text-align:right;">
1557801
</td>
</tr>
</tbody>
</table>
<p><br> To calculate EVPI, we average NMBs given current information and NMBs given perfect information across simulation draws.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">enmbpi &lt;-<span class="st"> </span><span class="kw">mean</span>(ce.nmb$nmbpi)
enmbci &lt;-<span class="st"> </span><span class="kw">mean</span>(ce.nmb$nmbci)
<span class="kw">print</span>(enmbpi)</code></pre></div>
<pre><code>## [1] 1580843</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(enmbci)</code></pre></div>
<pre><code>## [1] 1539987</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(enmbpi -<span class="st"> </span>enmbci)</code></pre></div>
<pre><code>## [1] 40855.48</code></pre>
<p>The <code>icea</code> function performs this same calculation across all simulation draws from the PSA and for a number of values of willingness to pay values <span class="math inline">\(k\)</span>. A plot by group of the the EVPI for different values of <span class="math inline">\(k\)</span> is shown below. The kinks in the plot represent values of <span class="math inline">\(k\)</span> where the optimal arm changes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(icea.dt$evpi, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> evpi)) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_line</a></span>() +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/facet_wrap">facet_wrap</a></span>(~grp) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"Willingess to pay"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="st">"Expected value of perfect information"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> comma) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_y_continuous</a></span>(<span class="dt">label =</span> scales::dollar) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_hue">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Arm"</span>)</code></pre></div>
<p><img src="cea-vignette_files/figure-html/evpi_plot-1.png" width="672"></p>
<p>We might also be interested in aggregating across subgroups. In particular, the total EVPI can be calculated as a weighted average of the group specific EVPIs,</p>
<p><span class="math display">\[
\begin{aligned}
totEVPI &amp;= \sum_{g=1}^{G} w_g EVPI_g,
\end{aligned}
\]</span> where <span class="math inline">\(w_g \in (0, 1)\)</span> is a weight denoting that proportion of the population represented by subgroup <span class="math inline">\(g\)</span> and <span class="math inline">\(\sum_{g=1}^{G} w_g = 1\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">w.dt &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/data.table/topics/data.table">data.table</a></span>(<span class="dt">grp =</span> <span class="kw">paste0</span>(<span class="st">"Group "</span>, <span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">2</span>)), <span class="dt">w =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, .<span class="dv">75</span>))
evpi &lt;-<span class="st"> </span>icea.dt$evpi
evpi &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/data.table/topics/merge">merge</a></span>(evpi, w.dt, <span class="dt">by =</span> <span class="st">"grp"</span>)
totevpi &lt;-<span class="st"> </span>evpi[,<span class="kw">lapply</span>(.SD, weighted.mean, <span class="dt">w =</span> w),
                by =<span class="st"> "k"</span>, .SDcols =<span class="st"> </span><span class="kw">c</span>(<span class="st">"evpi"</span>)]
<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(totevpi, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> evpi)) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_line</a></span>() +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"Willingess to pay"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="st">"Total EVPI"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> comma) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_y_continuous</a></span>(<span class="dt">label =</span> scales::dollar) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_hue">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Arm"</span>)</code></pre></div>
<p><img src="cea-vignette_files/figure-html/totevpi-1.png" width="672"></p>
</div>
<div id="distribution-of-health-and-cost-outcomes" class="section level2">
<h2 class="hasAnchor">
<a href="#distribution-of-health-and-cost-outcomes" class="anchor"></a>Distribution of health and cost outcomes</h2>
<p><code>icea</code> produces means, 2.5% quantiles, and 97.5% quantiles for costs and efficacy.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(icea.dt$summary)</code></pre></div>
<pre><code>##      arm     grp    e_mean  e_lower   e_upper       c_mean      c_lower
## 1: Arm 1 Group 1  8.004247 7.634748  8.422200     7.396253     6.085974
## 2: Arm 2 Group 1  9.936632 8.400865 11.455849 60307.349689 45226.901130
## 3: Arm 3 Group 1  8.464217 7.347104  9.550227 60482.110312 44000.176618
## 4: Arm 1 Group 2  8.013237 7.619150  8.408395     7.440276     6.086942
## 5: Arm 2 Group 2 10.504778 9.081556 11.981252 60765.550550 44486.837737
## 6: Arm 3 Group 2 11.003931 9.758687 12.187397 60929.097949 45251.388164
##         c_upper
## 1:     8.843086
## 2: 79243.796072
## 3: 78333.449529
## 4:     8.923828
## 5: 80400.431986
## 6: 79385.186605</code></pre>
<p>In addition, if the user would like to examine outcomes other than those specified this summary table, then they can generate a custom table of summary output. The custom table can contain any outcomes as long as they are specified in addition to the <code>sim</code>, <code>arm</code>, <code>e</code>, and <code>c</code> columns in the posterior distribution data table. The default is to estimate means, the 2.5% quantile, and the 97.5% quantile for each variable, but any custom function can used. Below, we create a hypothetical variable for life-years and create a table summarizing our estimates of costs, QALYs and life-years. A custom function, identical to the default option, is entered into the function for illustrative purposes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ce &lt;-<span class="st"> </span>ce[, lys :<span class="er">=</span><span class="st"> </span>qalys *<span class="st"> </span><span class="fl">1.5</span>]
cea.fun &lt;-<span class="st"> </span>function(x) <span class="kw">list</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(x), <span class="dt">quant =</span> <span class="kw">quantile</span>(x, <span class="kw">c</span>(.<span class="dv">025</span>, .<span class="dv">975</span>)))
icea.custom.dt &lt;-<span class="st"> </span><span class="kw"><a href="../reference/icea.html">icea</a></span>(ce, <span class="dt">k =</span> <span class="kw">seq</span>(<span class="dv">0</span>, ktop, <span class="dv">500</span>), <span class="dt">sim =</span> <span class="st">"sim"</span>, <span class="dt">arm =</span> <span class="st">"arm"</span>,
               <span class="dt">grp =</span> <span class="st">"grp"</span>, <span class="dt">e =</span> <span class="st">"qalys"</span>, <span class="dt">c =</span> <span class="st">"cost"</span>,
               <span class="dt">custom_vars =</span> <span class="kw">c</span>(<span class="st">"cost"</span>, <span class="st">"lys"</span>, <span class="st">"qalys"</span>), 
               <span class="dt">custom_fun =</span> cea.fun)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">icea.custom.dt$custom.table</code></pre></div>
<pre><code>##      arm     grp    cost.mean cost.quant.2.5% cost.quant.97.5% lys.mean
## 1: Arm 1 Group 1     7.396253        6.085974         8.843086 12.00637
## 2: Arm 2 Group 1 60307.349689    45226.901130     79243.796072 14.90495
## 3: Arm 3 Group 1 60482.110312    44000.176618     78333.449529 12.69633
## 4: Arm 1 Group 2     7.440276        6.086942         8.923828 12.01986
## 5: Arm 2 Group 2 60765.550550    44486.837737     80400.431986 15.75717
## 6: Arm 3 Group 2 60929.097949    45251.388164     79385.186605 16.50590
##    lys.quant.2.5% lys.quant.97.5% qalys.mean qalys.quant.2.5%
## 1:       11.45212        12.63330   8.004247         7.634748
## 2:       12.60130        17.18377   9.936632         8.400865
## 3:       11.02066        14.32534   8.464217         7.347104
## 4:       11.42872        12.61259   8.013237         7.619150
## 5:       13.62233        17.97188  10.504778         9.081556
## 6:       14.63803        18.28110  11.003931         9.758687
##    qalys.quant.97.5%
## 1:          8.422200
## 2:         11.455849
## 3:          9.550227
## 4:          8.408395
## 5:         11.981252
## 6:         12.187397</code></pre>
</div>
<div id="cost-effectiveness-plane" class="section level2">
<h2 class="hasAnchor">
<a href="#cost-effectiveness-plane" class="anchor"></a>Cost-effectiveness plane</h2>
<p>The cost-effectiveness plane plots the incremental effectiveness of a treatment arm (relative to a comparator) against the incremental cost of the treatment arm. The plot is useful because it demonstrates both the uncertainty and the magnitude of the estimates. Each point on the plot is from a particular random draw from the PSA.</p>
<p>Data for plotting a cost-effectiveness plane comes from the <code>delta</code> output generated from the <code>icea_pw</code> function, which, for each sampled parameter set and treatment arm, estimates differences in costs, effectiveness, and any other variables specified in <code>custom_vars</code>relative to the comparator. The dotted line in the plot is the willingness to pay line, with slope equal to the value of <span class="math inline">\(k\)</span>. For a given <span class="math inline">\(k\)</span>, points below the line are cost-effective while those above it are not.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(icea.pw.dt$delta)</code></pre></div>
<pre><code>##    sim   arm     grp       ie       ic
## 1:   1 Arm 2 Group 1 1.738258 46452.51
## 2:   2 Arm 2 Group 1 1.799369 54221.03
## 3:   3 Arm 2 Group 1 1.277094 65312.05
## 4:   4 Arm 2 Group 1 2.196491 67136.89
## 5:   5 Arm 2 Group 1 1.532732 63610.60
## 6:   6 Arm 2 Group 1 2.878233 54929.95</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ylim &lt;-<span class="st"> </span><span class="kw">max</span>(icea.pw.dt$delta[, ic]) *<span class="st"> </span><span class="fl">1.1</span>
xlim &lt;-<span class="st"> </span><span class="kw">ceiling</span>(<span class="kw">max</span>(icea.pw.dt$delta[, ie]) *<span class="st"> </span><span class="fl">1.1</span>)
<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(icea.pw.dt$delta, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> ie, <span class="dt">y =</span> ic, <span class="dt">col =</span> <span class="kw">factor</span>(arm))) +<span class="st"> </span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_jitter">geom_jitter</a></span>(<span class="dt">size =</span> .<span class="dv">5</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/facet_wrap">facet_wrap</a></span>(~grp) +<span class="st"> </span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"Incremental QALYs"</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="st">"Incremental cost"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_y_continuous</a></span>(<span class="dt">label =</span> dollar, <span class="dt">limits =</span> <span class="kw">c</span>(-ylim, ylim)) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_x_continuous</a></span>(<span class="dt">limits =</span> <span class="kw">c</span>(-xlim, xlim), <span class="dt">breaks =</span> <span class="kw">seq</span>(-<span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">2</span>)) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_hue">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Arm"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_abline">geom_abline</a></span>(<span class="dt">slope =</span> <span class="dv">150000</span>, <span class="dt">linetype =</span> <span class="st">"dashed"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_abline">geom_hline</a></span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_abline">geom_vline</a></span>(<span class="dt">xintercept =</span> <span class="dv">0</span>)</code></pre></div>
<p><img src="cea-vignette_files/figure-html/ceplane_plot-1.png" width="672"></p>
</div>
<div id="cost-effectiveness-acceptability-curve-ceac" class="section level2">
<h2 class="hasAnchor">
<a href="#cost-effectiveness-acceptability-curve-ceac" class="anchor"></a>Cost-effectiveness acceptability curve (CEAC)</h2>
<p>The cost-effectiveness acceptability curve (CEAC) is similar to the MCE plot. The difference is that the CEAC compares each arm to a single comparator whereas the MCE plot considers all arms simultaneously. Output to produce a CEAC is generated from the <code>icea_pw</code> function.</p>
<p>The plot shows that, in subgroup 1, Arm 2 has larger NMBs than Arm 1 with very high probability for reasonable values of <span class="math inline">\(k\)</span>. Arm 3 also has higher NMBs than Arm 1 with probability over 1/2 for values of <span class="math inline">\(k\)</span> larger than 130,500. In group 2, both Arm 2 and Arm 3 have higher NMBs than Arm 1 for almost all values of <span class="math inline">\(k\)</span>, although this probability is larger for Arm 2 than Arm 3 when <span class="math inline">\(k\)</span> is smaller.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(icea.pw.dt$ceac, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> k, <span class="dt">y =</span> prob, <span class="dt">col =</span> <span class="kw">factor</span>(arm))) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_line</a></span>() +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/facet_wrap">facet_wrap</a></span>(~grp) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"Willingess to pay"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="st">"Probability most cost-effective"</span>) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_continuous">scale_x_continuous</a></span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, ktop, <span class="dv">100000</span>), <span class="dt">label =</span> comma) +
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>) +<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_hue">scale_colour_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Arm"</span>)</code></pre></div>
<p><img src="cea-vignette_files/figure-html/ceac_plot-1.png" width="672"></p>
</div>
<div id="credible-intervals-for-incremental-costs-and-effectiveness" class="section level2">
<h2 class="hasAnchor">
<a href="#credible-intervals-for-incremental-costs-and-effectiveness" class="anchor"></a>Credible intervals for incremental costs and effectiveness</h2>
<p>Similar to the <code>icea</code> function, <code>icea_pw</code> produces means, 2.5% quantiles, and 97.5% quantiles for incremental costs and incremental efficacy. The table also contains the ICER, which is equal to expected incremental costs divided by the measure of expected incremental efficacy.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(icea.pw.dt$summary)</code></pre></div>
<pre><code>##      arm     grp   ie_mean   ie_lower ie_upper  ic_mean ic_lower ic_upper
## 1: Arm 2 Group 1 1.9323847  0.3005849 3.498060 60299.95 45219.40 79237.04
## 2: Arm 3 Group 1 0.4599701 -0.6887310 1.571353 60474.71 43992.96 78326.54
## 3: Arm 2 Group 2 2.4915405  0.9484968 4.098820 60758.11 44479.51 80394.04
## 4: Arm 3 Group 2 2.9906933  1.6812037 4.222467 60921.66 45243.62 79377.80
##         icer
## 1:  31204.94
## 2: 131475.31
## 3:  24385.76
## 4:  20370.41</code></pre>
<p>Again similar to the <code>icea</code> function, the user can also estimate incremental effects for outcome variables not included in the summary table.</p>
</div>
</div>
<div id="value-of-individualized-care" class="section level1">
<h1 class="hasAnchor">
<a href="#value-of-individualized-care" class="anchor"></a>Value of individualized care</h1>
<p>The previous analyses allow NMBs and optimal treatment decisions to vary by subgroup. In contrast, most CEAs estimate the treatment, <span class="math inline">\(j^{*}\)</span>, that is optimal when averaging NMBs over the entire population. In particular, if the population is broken up into <span class="math inline">\(G\)</span> distinct subgroups, the optimal treatment is given by,</p>
<p><span class="math display">\[
\begin{aligned}
j^{*} = \text{argmax}_j \sum_{g=1}^{G} w_g E_{\theta}\left[NMB_g(j,\theta)\right].
\end{aligned}
\]</span></p>
<p><span class="citation">Basu and Meltzer (2007)</span> have shown that selecting subgroup specific treatments increases expected net benefits relative to this one-size fits all approach. They refer to additional net benefit as the expected value of individualized care (EPIC), which can be computed in terms of NMBs using the subgroup approach illustrated here as,</p>
<p><span class="math display">\[
\begin{aligned}
\sum_{g=1}^G w_g E_{\theta}\left[NMB_g(j^{*}_s,\theta)\right] - \sum_{g=1}^G w_g  E_{\theta}\left[NMB_g(j^{*},\theta)\right].
\end{aligned}
\]</span></p>
<p>We can estimate the value of individualized care as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ce &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/data.table/topics/merge">merge</a></span>(ce, w.dt, <span class="dt">by =</span> <span class="st">"grp"</span>)
totenmb &lt;-<span class="st"> </span>ce[, .(<span class="dt">totenmb =</span> <span class="kw">weighted.mean</span>(nmb, <span class="dt">w =</span> w)), by =<span class="st"> </span><span class="kw">c</span>(<span class="st">"arm"</span>)]</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ptenmb.grp.max &lt;-<span class="st"> </span><span class="kw">apply</span>(<span class="kw">as.matrix</span>(enmb[, -<span class="dv">1</span>]), <span class="dv">2</span>, max)
ptenmb.max &lt;-<span class="st"> </span><span class="kw">sum</span>(ptenmb.grp.max *<span class="st"> </span>w.dt$w)
tenmb.max &lt;-<span class="st"> </span><span class="kw">max</span>(totenmb$totenmb)
tnmb &lt;-<span class="st"> </span><span class="kw">c</span>(ptenmb.max, tenmb.max)
<span class="kw">names</span>(tnmb) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">"Personalized total TENMB"</span>, <span class="st">"One-size fits all TENMB"</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">evic &lt;-<span class="st"> </span>tnmb[<span class="dv">1</span>] -<span class="st"> </span>tnmb[<span class="dv">2</span>]
<span class="kw">names</span>(evic) &lt;-<span class="st"> "EVIC"</span>
<span class="kw">print</span>(evic)</code></pre></div>
<pre><code>##     EVIC 
## 55259.24</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(evic/<span class="dv">150000</span>)</code></pre></div>
<pre><code>##      EVIC 
## 0.3683949</code></pre>
<p>Our estimate of the EVIC is $55,259, or in terms of net health benefits, 0.368 QALYs.</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-baio2012bayesian">
<p>Baio, Gianluca. 2012. <em>Bayesian Methods in Health Economics</em>. CRC Press.</p>
</div>
<div id="ref-baio2015probabilistic">
<p>Baio, Gianluca, and A Philip Dawid. 2015. “Probabilistic Sensitivity Analysis in Health Economics.” <em>Statistical Methods in Medical Research</em> 24 (6). SAGE Publications Sage UK: London, England: 615–34.</p>
</div>
<div id="ref-basu2007value">
<p>Basu, Anirban, and David Meltzer. 2007. “Value of Information on Preference Heterogeneity and Individualized Care.” <em>Medical Decision Making</em> 27 (2). Sage Publications: 112–27.</p>
</div>
<div id="ref-espinoza2014value">
<p>Espinoza, Manuel A, Andrea Manca, Karl Claxton, and Mark J Sculpher. 2014. “The Value of Heterogeneity for Cost-Effectiveness Subgroup Analysis: Conceptual Framework and Application.” <em>Medical Decision Making</em> 34 (8). Sage Publications Sage CA: Los Angeles, CA: 951–64.</p>
</div>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#overview">Overview</a></li>
      <li><a href="#net-monetary-benefits">Net monetary benefits</a></li>
      <li>
<a href="#probabilistic-sensitivity-analysis">Probabilistic sensitivity analysis</a><ul class="nav nav-pills nav-stacked">
<li><a href="#probability-most-cost-effective">Probability most cost-effective</a></li>
      <li><a href="#value-of-perfect-information">Value of perfect information</a></li>
      <li><a href="#distribution-of-health-and-cost-outcomes">Distribution of health and cost outcomes</a></li>
      <li><a href="#cost-effectiveness-plane">Cost-effectiveness plane</a></li>
      <li><a href="#cost-effectiveness-acceptability-curve-ceac">Cost-effectiveness acceptability curve (CEAC)</a></li>
      <li><a href="#credible-intervals-for-incremental-costs-and-effectiveness">Credible intervals for incremental costs and effectiveness</a></li>
      </ul>
</li>
      <li><a href="#value-of-individualized-care">Value of individualized care</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Devin Incerti.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://hadley.github.io/pkgdown/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  </body>
</html>
