# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecmax_index <- function(x) {
    .Call('hesim_vecmax_index', PACKAGE = 'hesim', x)
}

vecmax <- function(x) {
    .Call('hesim_vecmax', PACKAGE = 'hesim', x)
}

rowmaxC <- function(x) {
    .Call('hesim_rowmaxC', PACKAGE = 'hesim', x)
}

stdmean <- function(v) {
    .Call('hesim_stdmean', PACKAGE = 'hesim', v)
}

rowmax_indC <- function(x) {
    .Call('hesim_rowmax_indC', PACKAGE = 'hesim', x)
}

incr_effectC <- function(x, y, nsims, narms, ngrps) {
    .Call('hesim_incr_effectC', PACKAGE = 'hesim', x, y, nsims, narms, ngrps)
}

ceacC <- function(k, ie, ic, nsims, narms, ngrps) {
    .Call('hesim_ceacC', PACKAGE = 'hesim', k, ie, ic, nsims, narms, ngrps)
}

mceC <- function(k, e, c, nsims, narms, ngrps) {
    .Call('hesim_mceC', PACKAGE = 'hesim', k, e, c, nsims, narms, ngrps)
}

VstarC <- function(k, e, c, nsims, narms, ngrps) {
    .Call('hesim_VstarC', PACKAGE = 'hesim', k, e, c, nsims, narms, ngrps)
}

factorialC <- function(n) {
    .Call('hesim_factorialC', PACKAGE = 'hesim', n)
}

pv1 <- function(t1, t2, a, r) {
    .Call('hesim_pv1', PACKAGE = 'hesim', t1, t2, a, r)
}

exponent_int <- function(r, p, t, h) {
    .Call('hesim_exponent_int', PACKAGE = 'hesim', r, p, t, h)
}

poly_int <- function(r, p, t, h, a) {
    .Call('hesim_poly_int', PACKAGE = 'hesim', r, p, t, h, a)
}

pv_poly <- function(r, p, t1, t2, h, a) {
    .Call('hesim_pv_poly', PACKAGE = 'hesim', r, p, t1, t2, h, a)
}

rtruncnormC <- function(mean, sd, lower, upper) {
    .Call('hesim_rtruncnormC', PACKAGE = 'hesim', mean, sd, lower, upper)
}

qgompertzC <- function(p, shape, rate) {
    .Call('hesim_qgompertzC', PACKAGE = 'hesim', p, shape, rate)
}

rgompertzC <- function(shape, rate) {
    .Call('hesim_rgompertzC', PACKAGE = 'hesim', shape, rate)
}

qllogisC <- function(p, shape, scale, lt = 1L, lg = 0L) {
    .Call('hesim_qllogisC', PACKAGE = 'hesim', p, shape, scale, lt, lg)
}

rllogisC <- function(shape, scale) {
    .Call('hesim_rllogisC', PACKAGE = 'hesim', shape, scale)
}

rgengammaC <- function(mu, sigma, Q) {
    .Call('hesim_rgengammaC', PACKAGE = 'hesim', mu, sigma, Q)
}

rpwexp1C <- function(rate, time) {
    .Call('hesim_rpwexp1C', PACKAGE = 'hesim', rate, time)
}

rpwexpC <- function(rate, time) {
    .Call('hesim_rpwexpC', PACKAGE = 'hesim', rate, time)
}

rsurv <- function(location, anc1, dist, anc2 = 0.0) {
    .Call('hesim_rsurv', PACKAGE = 'hesim', location, anc1, dist, anc2)
}

rcat1C <- function(probs) {
    .Call('hesim_rcat1C', PACKAGE = 'hesim', probs)
}

rcatC <- function(probs) {
    .Call('hesim_rcatC', PACKAGE = 'hesim', probs)
}

notinvec <- function(item, v) {
    .Call('hesim_notinvec', PACKAGE = 'hesim', item, v)
}

nxttime <- function(current_time, time_jump, maxt) {
    .Call('hesim_nxttime', PACKAGE = 'hesim', current_time, time_jump, maxt)
}

matS <- function(index, cube, ntrans, k) {
    .Call('hesim_matS', PACKAGE = 'hesim', index, cube, ntrans, k)
}

updateAge <- function(x, age, col) {
    .Call('hesim_updateAge', PACKAGE = 'hesim', x, age, col)
}

#' @export
sim_ctsmC <- function(loc_beta, loc_x, dist, tmat, anc1, absorbing, maxt, maxage, agecol = -1L) {
    .Call('hesim_sim_ctsmC', PACKAGE = 'hesim', loc_beta, loc_x, dist, tmat, anc1, absorbing, maxt, maxage, agecol)
}

sim_state_t <- function(state, time, final, t, simindivs) {
    .Call('hesim_sim_state_t', PACKAGE = 'hesim', state, time, final, t, simindivs)
}

#' @export
sim_transprobC <- function(state, time, final, t, simindivs, nstates) {
    .Call('hesim_sim_transprobC', PACKAGE = 'hesim', state, time, final, t, simindivs, nstates)
}

matrix_byrow <- function(v, nrow, ncol) {
    .Call('hesim_matrix_byrow', PACKAGE = 'hesim', v, nrow, ncol)
}

matrix_bycol <- function(v, nrow, ncol) {
    .Call('hesim_matrix_bycol', PACKAGE = 'hesim', v, nrow, ncol)
}

list_to_vecmats <- function(L) {
    .Call('hesim_list_to_vecmats', PACKAGE = 'hesim', L)
}

list_loop <- function(L, beta, n) {
    .Call('hesim_list_loop', PACKAGE = 'hesim', L, beta, n)
}

cube_loop <- function(x, beta, n) {
    .Call('hesim_cube_loop', PACKAGE = 'hesim', x, beta, n)
}

