# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

markovCohort <- function(P, z0, ncycles, state_costs, state_qol, discount) {
    .Call('cea_markovCohort', PACKAGE = 'cea', P, z0, ncycles, state_costs, state_qol, discount)
}

