# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_apply_rr <- function(x, rr, index, complement) {
    .Call('_hesim_C_apply_rr', PACKAGE = 'hesim', x, rr, index, complement)
}

C_incr_effect <- function(x, y, n_samples, n_strategies, n_grps) {
    .Call('_hesim_C_incr_effect', PACKAGE = 'hesim', x, y, n_samples, n_strategies, n_grps)
}

C_ceac <- function(k, ie, ic, n_samples, n_strategies, n_grps) {
    .Call('_hesim_C_ceac', PACKAGE = 'hesim', k, ie, ic, n_samples, n_strategies, n_grps)
}

C_mce <- function(k, e, c, n_samples, n_strategies, n_grps) {
    .Call('_hesim_C_mce', PACKAGE = 'hesim', k, e, c, n_samples, n_strategies, n_grps)
}

C_enmbpi <- function(k, e, c, n_samples, n_strategies, n_grps) {
    .Call('_hesim_C_enmbpi', PACKAGE = 'hesim', k, e, c, n_samples, n_strategies, n_grps)
}

tmax_max <- function(m) {
    .Call('_hesim_tmax_max', PACKAGE = 'hesim', m)
}

C_ctstm_summary <- function(R_CtstmTrans, t, type) {
    .Call('_hesim_C_ctstm_summary', PACKAGE = 'hesim', R_CtstmTrans, t, type)
}

C_rgengamma <- function(n, mu, sigma, Q) {
    .Call('_hesim_C_rgengamma', PACKAGE = 'hesim', n, mu, sigma, Q)
}

C_rpwexp <- function(n, rate, time) {
    .Call('_hesim_C_rpwexp', PACKAGE = 'hesim', n, rate, time)
}

C_rcat <- function(n, probs) {
    .Call('_hesim_C_rcat', PACKAGE = 'hesim', n, probs)
}

C_rdirichlet_mat <- function(n, alpha) {
    .Call('_hesim_C_rdirichlet_mat', PACKAGE = 'hesim', n, alpha)
}

C_normalize_transprobs <- function(value) {
    invisible(.Call('_hesim_C_normalize_transprobs', PACKAGE = 'hesim', value))
}

C_cohort_dtstm_sim_stateprobs <- function(R_CohortDtstmTrans, times) {
    .Call('_hesim_C_cohort_dtstm_sim_stateprobs', PACKAGE = 'hesim', R_CohortDtstmTrans, times)
}

C_ctstm_sim_disease <- function(R_CtstmTrans, start_state, start_age, start_time, death_state, clock, reset_states, transition_types, max_t, max_age, progress) {
    .Call('_hesim_C_ctstm_sim_disease', PACKAGE = 'hesim', R_CtstmTrans, start_state, start_age, start_time, death_state, clock, reset_states, transition_types, max_t, max_age, progress)
}

C_ctstm_indiv_stateprobs <- function(R_disease_prog, t, n_samples, n_strategies, unique_strategy_id, strategy_index, n_grps, unique_grp_id, grp_index, n_states, n_patients) {
    .Call('_hesim_C_ctstm_indiv_stateprobs', PACKAGE = 'hesim', R_disease_prog, t, n_samples, n_strategies, unique_strategy_id, strategy_index, n_grps, unique_grp_id, grp_index, n_states, n_patients)
}

C_indiv_ctstm_wlos <- function(R_disease_prog, strategy_idx, patient_idx, R_StateVal, dr, type, max_time) {
    .Call('_hesim_C_indiv_ctstm_wlos', PACKAGE = 'hesim', R_disease_prog, strategy_idx, patient_idx, R_StateVal, dr, type, max_time)
}

C_indiv_ctstm_starting <- function(R_disease_prog, strategy_idx, patient_idx, R_StateVal, dr, type) {
    .Call('_hesim_C_indiv_ctstm_starting', PACKAGE = 'hesim', R_disease_prog, strategy_idx, patient_idx, R_StateVal, dr, type)
}

C_indiv_ctstm_trans <- function(R_CtstmTrans, R_disease_prog, strategy_idx, patient_idx, R_StateVal, dr, type) {
    .Call('_hesim_C_indiv_ctstm_trans', PACKAGE = 'hesim', R_CtstmTrans, R_disease_prog, strategy_idx, patient_idx, R_StateVal, dr, type)
}

C_indiv_ctstm_los <- function(R_disease_prog, strategy_idx, patient_idx, dr) {
    .Call('_hesim_C_indiv_ctstm_los', PACKAGE = 'hesim', R_disease_prog, strategy_idx, patient_idx, dr)
}

C_psm_curves_summary <- function(R_PsmCurves, x, type, dr) {
    .Call('_hesim_C_psm_curves_summary', PACKAGE = 'hesim', R_PsmCurves, x, type, dr)
}

C_psm_sim_stateprobs <- function(surv) {
    .Call('_hesim_C_psm_sim_stateprobs', PACKAGE = 'hesim', surv)
}

C_statevals_sim <- function(R_StateVals, times, type) {
    .Call('_hesim_C_statevals_sim', PACKAGE = 'hesim', R_StateVals, times, type)
}

C_sim_ev <- function(R_stateprobs, R_statevals, dr, categories, times, method = "trapz") {
    .Call('_hesim_C_sim_ev', PACKAGE = 'hesim', R_stateprobs, R_statevals, dr, categories, times, method)
}

C_sim_los <- function(stateprobs, n_obs, dr, times, integrate_method = "trapz") {
    .Call('_hesim_C_sim_los', PACKAGE = 'hesim', stateprobs, n_obs, dr, times, integrate_method)
}

C_test_trapz <- function(x, y) {
    .Call('_hesim_C_test_trapz', PACKAGE = 'hesim', x, y)
}

C_test_is_absorbing <- function(m) {
    .Call('_hesim_C_test_is_absorbing', PACKAGE = 'hesim', m)
}

C_test_trans_mat_trans_id <- function(m, from_state) {
    .Call('_hesim_C_test_trans_mat_trans_id', PACKAGE = 'hesim', m, from_state)
}

C_test_trans_mat_to <- function(m, from_state) {
    .Call('_hesim_C_test_trans_mat_to', PACKAGE = 'hesim', m, from_state)
}

C_test_trans_mat_n_trans <- function(m) {
    .Call('_hesim_C_test_trans_mat_n_trans', PACKAGE = 'hesim', m)
}

C_test_rtruncnorm <- function(mean, sd, lower, upper) {
    .Call('_hesim_C_test_rtruncnorm', PACKAGE = 'hesim', mean, sd, lower, upper)
}

C_test_xptr_test_time_fun <- function(L) {
    .Call('_hesim_C_test_xptr_test_time_fun', PACKAGE = 'hesim', L)
}

C_test_obs_index <- function(R_input_data, strategy_index, patient_index, health_index = -1L) {
    .Call('_hesim_C_test_obs_index', PACKAGE = 'hesim', R_input_data, strategy_index, patient_index, health_index)
}

C_test_obs_index_ids <- function(R_input_data, strategy_index, patient_index, health_index, member) {
    .Call('_hesim_C_test_obs_index_ids', PACKAGE = 'hesim', R_input_data, strategy_index, patient_index, health_index, member)
}

test_quad_dnorm <- function(lower, upper) {
    .Call('_hesim_test_quad_dnorm', PACKAGE = 'hesim', lower, upper)
}

test_quad_ier1 <- function() {
    .Call('_hesim_test_quad_ier1', PACKAGE = 'hesim')
}

test_quad_ier4 <- function() {
    .Call('_hesim_test_quad_ier4', PACKAGE = 'hesim')
}

test_quad_ier5 <- function() {
    .Call('_hesim_test_quad_ier5', PACKAGE = 'hesim')
}

test_riemann_x2 <- function(x) {
    .Call('_hesim_test_riemann_x2', PACKAGE = 'hesim', x)
}

test_cum_riemann_x2 <- function(x) {
    .Call('_hesim_test_cum_riemann_x2', PACKAGE = 'hesim', x)
}

C_test_rtrunc_repeat <- function(lower, upper) {
    .Call('_hesim_C_test_rtrunc_repeat', PACKAGE = 'hesim', lower, upper)
}

C_test_rsurv <- function(time, cumhaz, time_inf = TRUE) {
    .Call('_hesim_C_test_rsurv', PACKAGE = 'hesim', time, cumhaz, time_inf)
}

C_test_add_constant_int <- function(v, value) {
    .Call('_hesim_C_test_add_constant_int', PACKAGE = 'hesim', v, value)
}

C_test_add_constant_double <- function(v, value) {
    .Call('_hesim_C_test_add_constant_double', PACKAGE = 'hesim', v, value)
}

C_test_pv <- function(z, r, t1, t2) {
    .Call('_hesim_C_test_pv', PACKAGE = 'hesim', z, r, t1, t2)
}

C_test_seq <- function(from, to, by) {
    .Call('_hesim_C_test_seq', PACKAGE = 'hesim', from, to, by)
}

C_test_max_lt <- function(v, value) {
    .Call('_hesim_C_test_max_lt', PACKAGE = 'hesim', v, value)
}

C_test_find_interval <- function(x, vec) {
    .Call('_hesim_C_test_find_interval', PACKAGE = 'hesim', x, vec)
}

C_test_is_member_of <- function(x, lookup) {
    .Call('_hesim_C_test_is_member_of', PACKAGE = 'hesim', x, lookup)
}

test_zeroin <- function() {
    .Call('_hesim_test_zeroin', PACKAGE = 'hesim')
}

C_rowmax <- function(x) {
    .Call('_hesim_C_rowmax', PACKAGE = 'hesim', x)
}

C_rowmax_index <- function(x) {
    .Call('_hesim_C_rowmax_index', PACKAGE = 'hesim', x)
}

